### ISSUE TITLE
A question about offload_copy

### ISSUE THREAD

**Issue by qianqing13579** [ROCmSoftwarePlatform/AMDMIGraphX#1026]
what is the meaning of offload_copy?why need offload_copy?what is the difference  between offload_copy and not offload_copy?

**Comment by scxiao** [comment]
offload_copy is related to the gpu target. If set to true, migraphx automatically copies model inputs from cpu memory to gpu memory and copies outputs from gpu memory back to host memory. So with offload_copy being true, a user can just put inputs in host memory, and after inference is done, a user can read contents from the output arguments directly.

On the other hand, if offload_copy is false, after compiling a program on the gpu target, a user has to put all inputs in gpu memory. After interference is done, the user has to copy outputs arguments from gpu memory back to host memory before he can read the output contents.

**Comment by qianqing13579** [comment]
@scxiao ，why is the default value of offload_copy false instead of true? If the default value of offload_copy is false,a user needs more operations to run a model.If the default value is true,it will be easier to use.

**Comment by pfultz2** [comment]
The C++ API is usually used for implementing backends in frameworks(such as onnx runtime, tensorflow, pytorch, etc). These frameworks already have buffers transferred on the GPU(also we could be running a partial graph), which is why it is false by default.

**Comment by qianqing13579** [comment]
@pfultz2 ,when we insert allocation in lowering pass, why need add parameter for the output node when the offload_copy is false,why not insert a hip::allocate op.

**Comment by qianqing13579** [comment]
@pfultz2 ,the source code is as follows
```cpp
instruction_ref insert_allocation(instruction_ref ins, const shape& s, std::string tag = "")
    {
        // Instruction's output is an input of the ret instruction
        if(offload_copy)
        {
            auto result = mod->insert_instruction(
                ins, make_op("hip::allocate", {{"shape", to_value(s)}, {"tag", std::move(tag)}}));
            return result;
        }

        auto ins_alias = instruction::get_output_alias(ins);
        if(last->name() == "@return" and tag.empty() and prog_output_names.count(ins_alias) > 0)
        {
            return mod->add_parameter(prog_output_names[ins_alias], s);
        }
        else if(ins == last and tag.empty())
        {
            return mod->add_parameter("output", s);
        }

        return mod->insert_instruction(
            ins, make_op("hip::allocate", {{"shape", to_value(s)}, {"tag", std::move(tag)}}));
    }
```
