### ISSUE TITLE
Use fp32 accumulation for fp16 GEMM

### ISSUE THREAD

**Issue by jspark1105** [ROCmSoftwarePlatform/AMDMIGraphX#1029]
https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/blob/46b0c33bc4004714e866d026802de7a2fde0285b/src/targets/gpu/gemm_impl.cpp#L67

Wonder we should set compute_type to rocblas_datatype_f32_r to use matrix unit.

**Comment by kahmed10** [comment]
Yes, that is correct. However, there are some other changes to this file for alpha and beta that also need to be made. I made some changes to this file on the "mi100_opts" branch that you can use for reference. We are in progress to generalize the compute type based on the hardware.

**Comment by kahmed10** [comment]
Resolved in #1085
