### ISSUE TITLE
ScatterElement op, add attribute reduction

### ISSUE THREAD

**Issue by scxiao** [ROCmSoftwarePlatform/AMDMIGraphX#1081]
Current implementation of the ScatterElement op is for the scatter op that does not have reduction attribute. But the ScatterElements has the attribute "reduction". So we need to add the attribute.

**Comment by scxiao** [comment]
We can also define an enum for the reduction types since it is used by both the scatterElements and ScatterND ops.

**Comment by bpickrel** [comment]
The op with name scatter is deprecated in Onnx in favor of ScatterElements per [onnx docs](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Scatter)  Do we want to rename our existing scatter?
