### ISSUE TITLE
How to use MLIR in MIGraphX?

### ISSUE THREAD

**Issue by qianqing13579** [ROCmSoftwarePlatform/AMDMIGraphX#1092]
There is a mlir_conv pass in migraphx,and I want to try it. How to do it?

**Comment by qianqing13579** [comment]
I have tried,but miirCreateHandle failed,I do not know why

**Comment by causten** [comment]
It's not ready for primetime yet.  We are still working through issues.

**Comment by pfultz2** [comment]
Yea mlir support is experimental at best, you need to install the mlir from commit 02078ce236ad90e3aec04c0c770ef5bfc99e49c2 from the ROCmSoftwarePlatform/llvm-project-mlir repo, like we do in our dockerfile here:

https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/blob/develop/Dockerfile#L93
