### ISSUE TITLE
Add stream syncing

### ISSUE THREAD

**Issue by pfultz2** [ROCmSoftwarePlatform/AMDMIGraphX#1112]
First we need to extend the `context` and add two methods:

```cpp
struct context
{
    // New methods to add:
    void wait_for(any_ptr queue);
    void finish_on(any_ptr queue);
    // Already included methods:
    any_ptr get_queue();
    void finish();
};
```

We can then add an `execution_environment` class which can be passed to `eval`:

```cpp
struct execution_environment
{
    any_ptr queue = nullptr;
    bool async = false;
};
```

The `eval` method will be update to call the context methods using this class. When `async` is `false`, it will call `ctx.finish()` at the start and end of running. When `async` is `true`, it will call `ctx.wait_for(env.queue)` when it starts running and then call `ctx.finish(env.queue)` when it finishes running.

We will then need to expose `execution_environment` to our API, and add a `run_async` method which takes the `execution_environment`. The original `run` method should become fully synchronous.

**Comment by causten** [comment]
Once this is done ORT can be updated to support it

**Comment by TedThemistokleous** [comment]
Completed as part of 5.3
