### ISSUE TITLE
same_type: clip: Types do not match

### ISSUE THREAD

**Issue by causten** [ROCmSoftwarePlatform/AMDMIGraphX#1119]
I hit this error while running a test...

```
RuntimeError: /code/AMDMIGraphX/code/AMDMIGraphX/src/include/migraphx/check_shapes.hpp:115: same_type: clip: Types do not match
```

Paul mentioned that using `add_common_op` in parse_clip

**Comment by pfultz2** [comment]
The datatypes for Clip onnx operator can be different so we need to use `add_common_op` in parse_clip.cpp to insert the operator instead. We can then remove the multibroadcast insertion as well since `add_common_op` will take care of that as well.

**Comment by umangyadav** [comment]
We have a more general good first existing issue at #935
