### ISSUE TITLE
Add half2 overloads to math.hpp

### ISSUE THREAD

**Issue by causten** [ROCmSoftwarePlatform/AMDMIGraphX#1127]
Also half4 /w split to call half2

Should also check what does hip provide in the hip/math_functions.h and hip/hip_fp16.h to see if additional overloads could be used.

**Comment by bpickrel** [comment]
rocm's hip files eg. /opt/rocm/hip/include/hip/hip_fp16.h

**Comment by pfultz2** [comment]
This is to update the [math.hpp](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/blob/develop/src/targets/gpu/kernels/include/migraphx/kernels/math.hpp) header used by the kernels. We need to add overloads for the math functions that have half2 versions in the first part.

The second part, we need to add overloads for half4 and split it into 2 half2 vectors and then call the half2 versions, and then merge it back to half4. For packing/splitting the vectors, we should have a `vec_packed_transform<N>` function(similar to the `vec_transform` functor), Here is quick prototype of that(you will need to implement the missing `vec_type` type trait):

```cpp
// Return a vector type of N from index i in another larger vector
// N will be 2 for half2 packing
template <index_int N, class T, class I>
constexpr auto vec_packed_at(T x, I i)
{
    if constexpr(vec_size<T>() == 0)
        return vec<T, N>{x};
    else
    {
        MIGRAPHX_ASSERT((i+N) < vec_size<T>());
        // TODO: vec_type type trait needs to be implemented
        vec<vec_type<T>, N> result;
        for(int j = 0; j < N; j++) {
            result[j] = x[i+j];
        }
        return result;
    }
}

template <index_int N, class... Ts>
constexpr auto vec_packed_transform(Ts... xs)
{
    return [=](auto f) {
        if constexpr(is_any_vec<Ts...>())
        {
            using type                  = decltype(f(vec_packed_at(xs, 0)...));
            constexpr auto size         = common_vec_size<Ts...>();
            safe_vec<type, size> result = {0};
            for(int i = 0; i < size / N; i++)
            {
                // Call the function with packed vectors
                safe_vec<type, N> r = f(vec_packed_at(xs, i)...);
                // Copy the packed vectors to the result
                for(int j = 0; j < N; j++)
                    result[i * N + j] = r[j];
            }
            return result;
        }
        else
        {
            return f(xs...);
        }
    };
}
```

This is part of the runtime compilation so using the gpu-driver can be useful for testing this.
