### ISSUE TITLE
No check for type mismatch (might need adding additional checks)

### ISSUE THREAD

**Issue by scxiao** [ROCmSoftwarePlatform/AMDMIGraphX#116]
For the following program: 

#include <iostream>
#include <vector>
#include <migraph/literal.hpp>
#include <migraph/operators.hpp>
#include <migraph/instruction.hpp>
#include <migraph/cpu/target.hpp>
#include <migraph/verify.hpp>
#include "test.hpp"

int main() {
    migraph::program p;

    std::vector<float> data(4 * 5);
    std::iota(data.begin(), data.end(), 0);
    migraph::shape s{migraph::shape::float_type, {4, 5}};

    auto a0 = p.add_literal(migraph::literal{s, data});
    p.add_instruction(migraph::op::sin{}, a0);
    p.compile(migraph::cpu::target{});
    auto result = p.eval({});
    std::vector<int> resData(4 * 5);
    result.visit([&](auto output) { resData.assign(output.begin(), output.end()); });

    std::cout << "res = " << std::endl;
    for_each(resData.begin(), resData.end(), [](int& i) { std::cout << i << "\t"; });
    std::cout << std::endl;

    return 0;
}

It can pass compilation without warning (input is of float and output is of int) and generate all 0s output. We may need checking to report type mismatch (at least warnings)...

**Comment by mvermeulen** [comment]
No change.
