### ISSUE TITLE
Resnet50 example: Failed reading onnx file: resnet50.onnx

### ISSUE THREAD

**Issue by xiaoxiao-arch** [ROCmSoftwarePlatform/AMDMIGraphX#1163]
Hi,

I keep having parser issue to read onnx file. I also tried full path with onnx file but still failed. can you tell me why it failed and how to fix it? is there any debugging document?

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
~/migraphx/AMDMIGraphX/examples/vision/python_resnet50/resnet50_inference.py in <module>
     94
     95
---> 96 model = migraphx.parse_onnx("resnet50.onnx")
     97 model.compile(migraphx.get_target("gpu"))
     98 model.print()     # Printed in terminal

RuntimeError: /home/xiaoxli/AMDMIGraphX/src/onnx/onnx_parser.cpp:194: parse_from: PARSE_FROM: Failed reading onnx file: resnet50.onnx

Thanks,
Xiaoxiao

**Comment by kahmed10** [comment]
On my end, it appears that the file being downloaded is not actually an onnx file. You can verify by opening the contents of resnet50.onnx. Try downloading this file here:

https://github.com/onnx/models/raw/main/vision/classification/resnet/model/resnet50-v2-7.onnx
Then rename to `resnet50.onnx`. See if that works.
