### ISSUE TITLE
Resnet50 example reports error, "hip_device: Failed to allocate stream"

### ISSUE THREAD

**Issue by xiaoxiao-arch** [ROCmSoftwarePlatform/AMDMIGraphX#1165]
Hi,

I am trying to run the resnet50 example on a 6800xt card. I am getting a hip_device error on "model.compile(migraphx.get_target("gpu"))". Does migraphx support 6800xt card? if it does, can you help to tell me how to fix it?
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
~/migraphx/AMDMIGraphX/examples/vision/python_resnet50/resnet50_inference.py in <module>
     95
     96 model = migraphx.parse_onnx("/home/xiaoxli/migraphx/AMDMIGraphX/examples/vision/python_resnet50/resnet50.onnx")
---> 97 model.compile(migraphx.get_target("gpu"))
     98 model.print()     # Printed in terminal
     99 cap = cv2.VideoCapture("/home/xiaoxli/migraphx/AMDMIGraphX/examples/vision/python_resnet50/sample_vid.mp4")

RuntimeError: /home/xiaoxli/AMDMIGraphX/src/targets/gpu/include/migraphx/gpu/context.hpp:36: hip_device: Failed to allocate stream

**Comment by kahmed10** [comment]
Which ROCm version are you using? 6800XT is officially supported on 5.0 and beyond, and should work unofficially on 4.5.

I've seen the error before if MIGraphX is not built for the correct target, or the GPU is not configured correctly. Have you tried HIP programs or using other libraries within ROCm?

**Comment by kahmed10** [comment]
Resolved via ensuring user was part of unix group `render` then logging out/logging back in:
`sudo usermod -aG render $USER`
