### ISSUE TITLE
Optimized the propagate_constant pass..

### ISSUE THREAD

**Issue by scxiao** [ROCmSoftwarePlatform/AMDMIGraphX#1166]
Right now, the propagate_constant pass is very slow in some case, one possible reason is the recursive call inside this pass, which may be of a time complexity of O(n2), we need to optimize this pass to make it run faster...

**Comment by causten** [comment]
This will be your 3rd assignment, slightly more challenging then the first two.  
Steps to reproduce

```
export MIGRAPHX_TRACE_PASSES=1
wget https://zenodo.org/record/3733910/files/model.onnx
/opt/rocm/bin/migraphx-driver perf ./model.onnx   --fill1 input_ids --fill1 segment_ids --input-dim @input_ids 1 384 --fp16
```
The 1 and 384 map to Batch Size and Sequence Length respectively.  

There is a lot of text that will print.  Eventually you will see the text below.  It will sit on the screen for a bit then move on...
    Module: main, Pass: propagate_constant

Now change the batch size to 16.  You will notice the `propagate_constant` pass will hang longer on the screen.

Note: You don't need to use the exact model, there are smaller ones that do the same thing.  I can share with you a smaller version of Bert. 

There is also a slightly less hang at "Eliminate Contiguous" Maybe the same efficiency can help with that one too, but probably you could use another issue for that one.
