### ISSUE TITLE
Fix warning in code bugprone-implicit-widening-of-multiplication-result

### ISSUE THREAD

**Issue by causten** [ROCmSoftwarePlatform/AMDMIGraphX#1176]
/data/chris/AMDMIGraphX/src/targets/gpu/kernels/include/migraphx/kernels/roialign.hpp:93:48: error: performing an implicit widening conversion to type 'const int64_t' (aka 'const long') of a multiplication performed in type 'unsigned int' [bugprone-implicit-widening-of-multiplication-result,-warnings-as-errors]
const int64_t count = bin_grid_size[0] * bin_grid_size[1];
^
/data/chris/AMDMIGraphX/src/targets/gpu/kernels/include/migraphx/kernels/roialign.hpp:93:48: note: make conversion explicit to silence this warning
const int64_t count = bin_grid_size[0] * bin_grid_size[1];
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
static_cast( )
/data/chris/AMDMIGraphX/src/targets/gpu/kernels/include/migraphx/kernels/roialign.hpp:93:48: note: perform multiplication in a wider type
const int64_t count = bin_grid_size[0] * bin_grid_size[1];
^~~~~~~~~~~~~~~~
static_cast( )

CMake Error at tidy-target-kernel_file_check-_data_chris_AMDMIGraphX_build_src_targets_gpu_kernels_include_migraphx_kernels_roialign_cpp.cmake:80 (message):
Clang tidy failed.

src/targets/gpu/CMakeFiles/tidy-target-kernel_file_check-_data_chris_AMDMIGraphX_build_src_targets_gpu_kernels_include_migraphx_kernels_roialign_cpp.dir/build.make:57: recipe for target 'src/targets/gpu/CMakeFiles/tidy-target-kernel_file_check-_data_chris_AMDMIGraphX_build_src_targets_gpu_kernels_i

**Comment by kahmed10** [comment]
Most of the changes here seem trivial, but we have a lot of fixes to make.
