### ISSUE TITLE
install prereq.sh script fails to due to locale problem, are you testing it?

### ISSUE THREAD

**Issue by gggh000** [ROCmSoftwarePlatform/AMDMIGraphX#1191]
rocm5.1.0
It is such a fundamental build error. build instruction clearly tells to use non-working script install_prereqs.sh which fails. Applying recommended export does not work either.

Traceback (most recent call last):
  File "/usr/local/bin/rbuild", line 11, in <module>
    load_entry_point('rbuild==0.0.1', 'console_scripts', 'rbuild')()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 760, in main
    _verify_python3_env()
  File "/usr/local/lib/python3.6/site-packages/click/_unicodefun.py", line 130, in _verify_python3_env
    " mitigation steps.{}".format(extra)
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment. Consult https://click.palletsprojects.com/python3/ for mitigation steps.

This system supports the C.UTF-8 locale which is recommended. You might be able to resolve your issue by exporting the following environment variables:

    export LC_ALL=C.UTF-8
    export LANG=C.UTF-8

**Comment by causten** [comment]
Thank you for bringing this to my attention.  We definitely do a lot of testing via containers and our two Dockerfiles ([hip-clang.docker](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/blob/develop/hip-clang.docker), and [Dockerfile](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/blob/develop/Dockerfile)), do indeed export those variables.  I'll dig in to this some more and come up with a proper fix
