### ISSUE TITLE
test build fails with rocm_clang_tidy_check

### ISSUE THREAD

**Issue by gggh000** [ROCmSoftwarePlatform/AMDMIGraphX#1205]
root@ixt-hq-178:~/ROCm-5.1/AMDMIGraphX/test/build# cmake ..
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
CMake Error at CMakeLists.txt:98 (rocm_clang_tidy_check):
  Unknown CMake command "rocm_clang_tidy_check".

CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.16)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
See also "/root/ROCm-5.1/AMDMIGraphX/test/build/CMakeFiles/CMakeOutput.log".
See also "/root/ROCm-5.1/AMDMIGraphX/test/build/CMakeFiles/CMakeError.log".
root@ixt-hq-178:~/ROCm-5.1/AMDMIGraphX/test/build# make -j8
make: *** No targets specified and no makefile found

**Comment by kahmed10** [comment]
This is because you care calling `cmake ..` which points to the `test` directory. There probably isn't a CMakeLists.txt file there. I believe you want to do `cmake ../..` to get to the right path of the CMakeLists.txt
