### ISSUE TITLE
Add support for SAME_UPPER and SAME_LOWER auto_pad for Convolution and MaxPool

### ISSUE THREAD

**Issue by wsttiger** [ROCmSoftwarePlatform/AMDMIGraphX#121]
We're not parsing this attribute for convolution or pooling which is leading to failure of reading certain ONNX files produced by CNTK. However, this feature is listed as `deprecated` in the ONNX standard. Not sure if it's worth implementing or not.

**Comment by kahmed10** [comment]
We will currently support SAME_UPPER as default. SAME_LOWER can be implemented using the Pad operator, but we did not see any models using this mode.
