### ISSUE TITLE
Add algebraic simplications for mul, div, add etc. 

### ISSUE THREAD

**Issue by umangyadav** [ROCmSoftwarePlatform/AMDMIGraphX#1236]
x * 1 = x
x / 1 = x
x * 0  = 0
x + 0 = x
x - 0 = x
x * 0 = 0 
x * -1 = -x 
x  / -1 = -x 
If x / 0 is detected anywhere throw errors. 

~~Consecutive const binary operations. 
y = (x + c1) + c2 --- > y = x + (c1+c2) -- > y = x + c3 where c3  = c1 + c2 const folded. 
y = ( x * c1 ) * c2 --- > y = x * (c1 * c2)~~
etc...

**Comment by TedThemistokleous** [comment]
Got something in the works for x*1 = x. 

Getting the odd identity(x) operation popping out. Thanks to your recent help, I was able to handle the 

x*1 and 1*x cases with matchers. 

Currently breaking another test for this though.

**Comment by TedThemistokleous** [comment]
Awesome. Thanks

**Comment by umangyadav** [comment]
Fixed with https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/pull/1281
