### ISSUE TITLE
#include <migraphx/program.hpp> error

### ISSUE THREAD

**Issue by 210210** [ROCmSoftwarePlatform/AMDMIGraphX#1277]
i want to use migraphx::program p create a program with my cmakefile,but appear a error,
![image](https://user-images.githubusercontent.com/50653255/176390217-3e1261ce-f430-42a6-9538-60cb6a1ca4bb.png)

what can i do to fix this

CMakeLists.txt:
![image](https://user-images.githubusercontent.com/50653255/176390542-db456ae1-1974-4d82-ab09-a6b53fb1b62e.png)

**Comment by CharlieL7** [comment]
What does your development environment look like? Did you install the migraphx library?

**Comment by umangyadav** [comment]
Looks like you are trying to use C++ API. You only need to include `<migraphx/migraphx.hpp>` 

You can take a look at one of the examples : [here](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/blob/develop/examples/migraphx/cpp_parse_load_save/parse_load_save.cpp) or [here](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/tree/develop/examples/vision/cpp_mnist)

To get `migraphx::program` , generally you need to import a model from either onnx or TensorFlow. 

e.g. `migraphx:: program p = parse_onnx("model.onnx", parse_options)`.

**Comment by jiaoyuming1** [comment]
The above seems to be because two header files(migraphx.hpp  program.hpp) cannot be included at the same time.
But I ran into a problem when using program.hpp builds IR, the following dynamic libraries cannot be found. Which library should I link again?
![image](https://user-images.githubusercontent.com/50188752/176582044-2d0c4e4f-08d8-4216-9c61-4ae8324c1be3.png)
Thanks

**Comment by umangyadav** [comment]
> The above seems to be because two header files(migraphx.hpp program.hpp) cannot be included at the same time. But I ran into a problem when using program.hpp builds IR, the following dynamic libraries cannot be found. Which library should I link again? ![image](https://user-images.githubusercontent.com/50188752/176582044-2d0c4e4f-08d8-4216-9c61-4ae8324c1be3.png)
> 
> #include <migraphx/program.hpp> int main() { migraphx::program p; return 0; }
> 
> Thanks
> 
> **update:** I have found it in build/lib/libmigraphx.so seems to contain all the link libraries,but it's not install to /opt/rcom/lib. Thanks again.

yes, you shouldn't include `program.hpp` if you are trying to use MIGraphX's C/C++ API. Only `migraphx.hpp` should be enough.

Make sure, you `export LD_LIBRARY_PATH=/opt/rocm/lib:$LD_LIBRARY_PATH`  

Try following examples link provided earlier.

**Comment by 210210** [comment]
> 
My problem is solved, thanks
