### ISSUE TITLE
CRNN model failed to run

### ISSUE THREAD

**Issue by qianqing13579** [ROCmSoftwarePlatform/AMDMIGraphX#1319]
I used migrapx-driver to test a CRNN model(Convolutional Recurrent Neural Network),but it failed to run.the migraphx is from commit f2531606c266dd548fee59f242849615cab7f613.

the command I used:
```
migraphx-driver perf --onnx dynamic_crnn_2048.onnx
```
the  download link of the model:
https://drive.google.com/file/d/18ftm_ve6vty7o5upiKbPGUuWL7wQ13ao/view?usp=sharing

**Comment by causten** [comment]
Dynamic models are not supported yet.  We did add support for the mlperf  RNN-T model at FP32.  In a future release Dynamic Shape support will be more generally available.  I'll assign this model to a member of the team to examine

**Comment by qianqing13579** [comment]
@causten ,I did not use dynamic shape,I just want to test the performance

**Comment by CharlieL7** [comment]
* Can you supply the outputted error?
* I cannot use the link provided, please use another service.

**Comment by qianqing13579** [comment]
@CharlieL7 , the model link: https://drive.google.com/file/d/18ftm_ve6vty7o5upiKbPGUuWL7wQ13ao/view?usp=sharing

**Comment by qianqing13579** [comment]
@CharlieL7 , the program will stop at the simplify_algebra pass,but when I remove find_splits in simplify_algebra pass,the program will output the error:

**Comment by CharlieL7** [comment]
The problem looks to be occurring during the model compilation. For me, it's not stopping at the simplify_algebra pass but instead getting killed during eliminate_contiguous.

**Comment by qianqing13579** [comment]
@CharlieL7 ，do you know why it gets killed during eliminate_contiguous

**Comment by qianqing13579** [comment]
@CharlieL7 ,the graph of the model is as follows:
[crnn_graph.log](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/files/9250745/crnn_graph.log)
the graph is too big!

**Comment by CharlieL7** [comment]
The LSTM nodes are unraveled during the rewrite_rnn pass, which is why the program becomes so large. I am looking into the issue, will likely take a while to pin down the bug.

**Comment by CharlieL7** [comment]
Looking into compiling faster, will likely need to do something different with the rewrite_rnn pass. For now, to get around the compile time you could save the model with the `--output` option of the driver.

**Comment by qianqing13579** [comment]
@CharlieL7 ，I use migraphx::save to save the CRNN model,but migraphx::load can not load the saved model. I do not know why

**Comment by qianqing13579** [comment]
@CharlieL7 ,I use migraphx::save to save the CRNN((Convolutional Recurrent Neural Network)) model successfully,but migraphx::load can not load the saved model. I do not know why.
