### ISSUE TITLE
How to use debug mode

### ISSUE THREAD

**Issue by qianqing13579** [ROCmSoftwarePlatform/AMDMIGraphX#1340]
I want to debug a model with migraphx. but I do not know how to use debug mode of migraphx.

**Comment by CharlieL7** [comment]
Depends on what you want to debug. If you want to have the traces of the compile or eval you can set the environment variables: `MIGRAPHX_TRACE_EVAL=1` or `MIGRAPHX_TRACE_COMPILE=1` when running the driver.

**Comment by qianqing13579** [comment]
@CharlieL7 ，I want to build migraphx in debug mode

**Comment by kahmed10** [comment]
You can change `CMAKE_BUILD_TYPE` to `Debug`, then recompile.
`cd {build_dir}; cmake -DCMAKE_BUILD_TYPE=Debug ..; make -j$(nproc)`

Then if you are using the driver, you can do something like `gdb driver` or `lldb driver`. If you put breakpoints, you may get a message about future library loads. That is normal.

**Comment by qianqing13579** [comment]
I tried,but an error occurs:
```
error: local memory (163840) exceeds limit (65536) in function '_ZN8migraphx9version_13gpu6device8launcherIZZNS2_23nary_broadcast_vec_implIZNS2_7greaterEP12ihipStream_tRKNS0_8argumentES9_S9_EUlT_T0_E_JS7_EEEvS6_SA_S7_S7_DpT0_ENKUlSA_SB_DpT1_E_clINS2_15hip_tensor_viewIDv4_hLj3EEESL_JSL_EEEDaSA_SB_SG_EUlSA_E_EEvSA_'
```

**Comment by CharlieL7** [comment]
That's an error from another part of the ROCm stack and LLVM when building in debug mode. Try using the RelWithDebInfo build type.

**Comment by qianqing13579** [comment]
thanks
