### ISSUE TITLE
an error about parse_if

### ISSUE THREAD

**Issue by qianqing13579** [ROCmSoftwarePlatform/AMDMIGraphX#1344]
I want to use migraphx-driver to test a model but an error occurs in migraphx::parse_onnx. The migraphx is from commit f2531606c266dd548fee59f242849615cab7f613
the command I used:/opt/rocm/bin/migraphx-driver perf TextLinePred_0722_v1.onnx
the outputs: src/onnx/parse_if.cpp:72: parse: PARSE_IF: then and else sub_grahps must have same output shapes!
the model link: https://drive.google.com/file/d/18p1AAdjCA3kr1zd7lkRfmfcFOC7layrW/view?usp=sharing

**Comment by CharlieL7** [comment]
This looks related to a similar issue we've been seeing for ResNext50. There's a PR in progress for the If operator that needs more work. @TedThemistokleous

**Comment by TedThemistokleous** [comment]
Potentially. This looks like this was before we added the fix Charlie and I did with our input constants as well. Let me look at the model on netron and see why this is failing.

**Comment by TedThemistokleous** [comment]
Confirmed its another issue with IF being parsed in but shapes not interpreting outputs based on stride

```
module: "If_641_else"
If_641_else:@0 = identity(main:@637) -> float_type, {1, 3, 1, 1}, {3, 1, 1, 1}
If_641_else:@1 = @return(If_641_else:@0)

module: "If_641_if"
If_641_if:@0 = squeeze[axes={2}](main:@637) -> float_type, {1, 3, 1}, {3, 1, 1}
If_641_if:@1 = @return(If_641_if:@0)


terminate called after throwing an instance of 'migraphx::version_1::exception'
  what():  /code/AMDMIGraphX/src/onnx/parse_if.cpp:74: parse: PARSE_IF: If_641 then and else sub_grahps must have same output shapes!
Aborted (core dumped)
root@c285b5e687d8:/code/AMDMIGraphX/build# 
```
The branch you tried this on @qianqing13579 checks strict shapes. It's an issue we're currently working on with our shapes IF operator as the output case you're hitting requires dynamic output. We've seen this similar issues in a few other model's we've tested (#1283).

**Comment by qianqing13579** [comment]
@CharlieL7 ,@TedThemistokleous , I think there is a bug in migraphx. the IF operator definition(https://github.com/onnx/onnx/blob/main/docs/Operators.md#If) says that The number of outputs must match the number of outputs in the else_branch instead of they must have same output shapes!so the exception code of src/onnx/parse_if.cpp:74 should be removed,and then the model can run successfully

**Comment by TedThemistokleous** [comment]
@qianqing13579  good news this is completed and needs to finish up review.

**Comment by TedThemistokleous** [comment]
hi @qianqing13579 , Ive gotten past the error with parse_if and fixed this issue. 

I was able to run your network with the latest fix before it's gone into our develop branch

Here's a breakdown of the results when running
`bin/driver perf  ~/Downloads/TextLinePred_0722_v1.onnx  --input-dim @src 1 3 25 25  --gpu`

```
Summary:
gpu::convolution: 7.38415ms / 39 = 0.189337ms, 68%
gpu::miopen_fusion: 1.74431ms / 25 = 0.0697724ms, 16%
gpu::code_object::add_relu_kernel: 0.443138ms / 22 = 0.0201427ms, 5%
gpu::code_object::add_add_relu_kernel: 0.226756ms / 11 = 0.0206142ms, 3%
gpu::code_object::sub_mul_add_kernel: 0.211109ms / 10 = 0.0211109ms, 2%
gpu::code_object::concat_kernel: 0.199436ms / 10 = 0.0199436ms, 2%
load: 0.131432ms / 166 = 0.000791762ms, 2%
hip::hip_copy_literal: 0.120674ms / 139 = 0.000868155ms, 2%
gpu::code_object::gather_kernel: 0.0944559ms / 4 = 0.023614ms, 1%
gpu::code_object::contiguous_kernel: 0.0790783ms / 4 = 0.0197696ms, 1%
gpu::gemm: 0.0789602ms / 1 = 0.0789602ms, 1%
broadcast: 0.0617541ms / 59 = 0.00104668ms, 1%
gpu::code_object::concat_add_relu_kernel: 0.0426691ms / 2 = 0.0213346ms, 1%
slice: 0.0276975ms / 25 = 0.0011079ms, 1%
gpu::pooling: 0.0273466ms / 1 = 0.0273466ms, 1%
gpu::code_object::reduce_kernel: 0.0211819ms / 1 = 0.0211819ms, 1%
reshape: 0.00837126ms / 9 = 0.00093014ms, 1%
@param: 0.00260844ms / 4 = 0.00065211ms, 1%
transpose: 0.0024983ms / 3 = 0.000832767ms, 1%
step: 0.00231824ms / 2 = 0.00115912ms, 1%
squeeze: 0.00202164ms / 2 = 0.00101082ms, 1%
multibroadcast: 0.0013198ms / 1 = 0.0013198ms, 1%
check_context::migraphx::version_1::gpu::context: 0.00102604ms / 1 = 0.00102604ms, 1%
hip::hip_allocate_memory: 0.00095902ms / 1 = 0.00095902ms, 1%

Batch size: 1
Rate: 129.748/sec
Total time: 7.70722ms
Total instructions time: 10.9153ms
Overhead time: 0.143831ms, -3.
[TestLinePred_0722_v1_output.txt](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/files/10550667/TestLinePred_0722_v1_output.txt)
20805ms
Overhead: 2%, -42%

```
I've attached a longer log of the output too.
