### ISSUE TITLE
Gemm operator beta value issue

### ISSUE THREAD

**Issue by kahmed10** [ROCmSoftwarePlatform/AMDMIGraphX#137]
The equation in Onnx for Gemm is Y=alpha*A*B + beta*C, where alpha=1,beta=1 by default. However, in our implementation, because of our gemm library calls, we do not directly output Y. Instead, we use C as the output matrix and set beta=0. Therefore, in the current Onnx models, we are incorrectly setting beta=0 which is not the intended behavior.

**Comment by scxiao** [comment]
according to the specification of the numpy.matmul, the behavior depends on the arguments in the following way.

    1. If both arguments are 2-D they are multiplied like conventional matrices.
    2. If either argument is N-D, N > 2, it is treated as a stack of matrices residing in the last two indexes and broadcast accordingly.
    3. If the first argument is 1-D, it is promoted to a matrix by prepending a 1 to its dimensions. After matrix multiplication the prepended 1 is removed.
    4. If the second argument is 1-D, it is promoted to a matrix by appending a 1 to its dimensions. After matrix multiplication the appended 1 is removed.

Current implementation only satisfies item 1, we did some extension to satisfy item 2. Items 3 and Items 4 are tracked in issue #196 and will be implemented in release 0.3
