### ISSUE TITLE
a mistake about fuse_ops.cpp

### ISSUE THREAD

**Issue by qianqing13579** [ROCmSoftwarePlatform/AMDMIGraphX#1381]
the following line in fuse_ops.cpp has a mistake:
(https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/blob/827baeec9f99b76804b2ac3b70ef1a1786630ebe/src/targets/gpu/fuse_ops.cpp#L262)

I think it should be:
struct hip_add_sigmoid : binary_device<hip_add_sigmoid, &device::add_sigmoid>

**Comment by umangyadav** [comment]
Yes that's a typo. Thanks for surfacing this.

**Comment by umangyadav** [comment]
Fixed with #1385
