### ISSUE TITLE
runtime issues after updating to ROCm 2.0 and MIOpen 1.7

### ISSUE THREAD

**Issue by mvermeulen** [ROCmSoftwarePlatform/AMDMIGraphX#146]
Updated system to ROCm 2.0 and have the following installed on Ubuntu 16.04:

ii  rocm-clang-ocl                             0.3.0-7997136                                amd64        OpenCL compilation with clang compiler.
ii  rocm-cmake                                 0.2.0-6240bb3                                amd64        rocm-cmake built using CMake
ii  rocm-dev                                   2.0.89                                       amd64        Radeon Open Compute (ROCm) Runtime software stack
ii  rocm-device-libs                           0.0.1                                        amd64        Radeon Open Compute - device libraries
ii  rocm-dkms                                  2.0.89                                       amd64        Radeon Open Compute (ROCm) Runtime software stack
ii  rocm-libs                                  2.0.89                                       amd64        Radeon Open Compute (ROCm) Runtime software stack
ii  rocm-opencl                                1.2.0-2018121317                             amd64        OpenCL/ROCm
ii  rocm-opencl-dev                            1.2.0-2018121317                             amd64        OpenCL/ROCm
ii  rocm-profiler                              5.6.7219                                     amd64        The ROCm-Profiler is a command-line profiler for profiling applications running on the Radeon Open Compute platforms.
ii  rocm-smi                                   1.0.0-95-g3512a29                            amd64        System Management Interface for ROCm
ii  rocm-utils                                 2.0.89                                       amd64        Radeon Open Compute (ROCm) Runtime software stack
ii  rocminfo                                   1.0.0-1bb0ccc                                amd64        Radeon Open Compute (ROCm) Runtime rocminfo tool
ii  miopen-hip                                 1.7.0-49c48917                               amd64        AMD's DNN Library
ii  miopengemm                                 1.1.5-9547fb9                                amd64        A tool for generating OpenCL matrix multiplication (GEMM) kernel

After this the MIGraphX unit tests fail to run. In particular, the following are sent to stderr:
MIOpen Error: /home/dlowell/MIOpenPrivate/src/include/miopen/hipoc_kernel.hpp:200: Failed to get function: MIOpenActiveFwdLite from /home/mev/.cache/miopen/1.7.0/687217
f358041cfac44f209281b3d793/MIOpenNeuron.cl.o hipErrorNotFound
MIOpen Error: /home/dlowell/MIOpenPrivate/src/include/miopen/hipoc_kernel.hpp:200: Failed to get function: MIOpenActiveFwdLite from /home/mev/.cache/miopen/1.7.0/1334b6
e929d87130b3ce39c0188ded63/MIOpenNeuron.cl.o hipErrorNotFound
MIOpen Error: /home/dlowell/MIOpenPrivate/src/include/miopen/hipoc_kernel.hpp:200: Failed to get function: MIOpenActiveFwdLite from /home/mev/.cache/miopen/1.7.0/1334b6
e929d87130b3ce39c0188ded63/MIOpenNeuron.cl.o hipErrorNotFound
MIOpen Error: /home/dlowell/MIOpenPrivate/src/include/miopen/hipoc_kernel.hpp:200: Failed to get function: MIOpenActiveFwdLite from /home/mev/.cache/miopen/1.7.0/687217
f358041cfac44f209281b3d793/MIOpenNeuron.cl.o hipErrorNotFound
MIOpen Error: /home/dlowell/MIOpenPrivate/src/include/miopen/hipoc_kernel.hpp:200: Failed to get function: SoftmaxForward from /home/mev/.cache/miopen/1.7.0/509089a17f3
53633f9579aa70b046949/MIOpenSoftmax.cl.o hipErrorNotFound
MIOpen Error: /home/dlowell/MIOpenPrivate/src/include/miopen/hipoc_kernel.hpp:200: Failed to get function: SoftmaxForward from /home/mev/.cache/miopen/1.7.0/41c5aec8922
5214f431339ee5e55bf9d/MIOpenSoftmax.cl.o hipErrorNotFound
MIOpen Error: /home/dlowell/MIOpenPrivate/src/include/miopen/hipoc_kernel.hpp:200: Failed to get function: Im2Col from /home/mev/.cache/miopen/1.7.0/3b9f54c4eb67fa4abde
984392c1a3ed4/MIOpenUtilKernels.cl.o hipErrorNotFound

Any clues @daniellowell @pfultz2 ?

**Comment by pfultz2** [comment]
This is the issue with clang-ocl not updating correctly. You need to explicitly call the version and delete the miopen cache.

**Comment by mvermeulen** [comment]
Installed rocm-clang-ocl-0.3.0-688fe5d revision and now unit tests pass without issue.
