### ISSUE TITLE
How to use MIOpen to develop LSTM op in MIGraphX?

### ISSUE THREAD

**Issue by qianqing13579** [ROCmSoftwarePlatform/AMDMIGraphX#1481]
I want to use MIOpen to develop LSTM op like pytorch. but  I do not know how

**Comment by CharlieL7** [comment]
MIGraphX supports the ONNX LSTM operator: https://github.com/onnx/onnx/blob/main/docs/Operators.md#LSTM. I'm not familiar with PyTorch's implementation of LSTM, but these should be compatible.
