### ISSUE TITLE
FP16 sqdiff and reduce_mean ops inaccurate

### ISSUE THREAD

**Issue by shivadbhavsar** [ROCmSoftwarePlatform/AMDMIGraphX#1497]
Attached mxr contains a small set of instructions found in the VAE Decoder model in the stable diffusion pipeline. The bug can be reproduced using the verify command.

FP32 works:
```
migraphx-driver verify sqdiff.mxr
```

FP16 fails (by large margins not explained by the lower precision)
```
migraphx-driver verify sqdiff.mxr --fp16
```

[sqdiff.zip](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/files/10262748/sqdiff.zip)

Program for reference:
```
module: "main"
x1 = @param:x1 -> float_type, {1, 512, 64, 64}, {2097152, 4096, 64, 1}
main:@1 = @literal{ ... } -> float_type, {512, 512, 3, 3}, {4608, 9, 3, 1}
x0 = @param:x0 -> float_type, {1, 512, 64, 64}, {2097152, 4096, 64, 1}
main:@3 = convolution[padding={1, 1, 1, 1},stride={1, 1},dilation={1, 1},group=1,padding_mode=0](x0,main:@1) -> float_type, {1, 512, 64, 64}, {2097152, 4096, 64, 1}
main:@4 = add(x1,main:@3) -> float_type, {1, 512, 64, 64}, {2097152, 4096, 64, 1}
main:@5 = reshape[dims={1, 32, 65536}](main:@4) -> float_type, {1, 32, 65536}, {2097152, 65536, 1}
main:@6 = reduce_mean[axes={2}](main:@5) -> float_type, {1, 32, 1}, {32, 1, 1}
main:@7 = multibroadcast[out_lens={1, 32, 65536},out_dyn_dims={}](main:@6) -> float_type, {1, 32, 65536}, {32, 1, 0}
main:@8 = sqdiff(main:@5,main:@7) -> float_type, {1, 32, 65536}, {2097152, 65536, 1}
main:@9 = @return(main:@8)

```

**Comment by kahmed10** [comment]
The issue can be easily reproduced by isolating the `reduce_mean` in the above program. Input shape of `{half_type, [1, 32, 65536]}` with axis=2. Results are either 0s or NaNs.

**Comment by pfultz2** [comment]
I see the issue. `65536` is out of range for half so we cant even do the initial division. We probably need to switch to use a `float` accumulator instead of half.

**Comment by kahmed10** [comment]
It looks like changing the accumulator type resolves the issue.
