### ISSUE TITLE
Support user-driven tuning for rocBLAS inside  MIGraphX

### ISSUE THREAD

**Issue by umangyadav** [ROCmSoftwarePlatform/AMDMIGraphX#1553]
rocBLAS has released [beta API](https://github.com/ROCmSoftwarePlatform/rocBLAS-internal/blob/develop/library/include/internal/rocblas-beta.h) to allow [users to find out](https://github.com/ROCmSoftwarePlatform/rocBLAS-internal/blob/develop/clients/samples/example_user_driven_tuning.cpp) the best solver/implementation for the given GEMM problem. 

Currently, MIGraphX relies on the default solution from rocBLAS. MIGraphX can make use of BETA API during the compile time and can serialize the solution index to use it in later inference runs. 

This could potentially yield better performance on users' hardware where rocBLAS's default solution may not work as efficiently or if rocBLAS doesn't have tuned parameters for the user's problem or their hardware setup. 

[How it works in rocBLAS : ](https://github.com/ROCmSoftwarePlatform/rocBLAS-internal/blob/develop/clients/samples/example_user_driven_tuning.cpp)

1. Get maximum applicable rocBLAS solutions to users' problem 
2. Get solution_index of those solutions. 
3. Profile each rocBLAS solution to  find out best solution 
4. Save best solution_index for later use. 

TO-DOs in MIGraphX : 

- [ ] rocBLAS function calls requires a long list of arguments to pass. Refactor current code such that, we encapsulate building all those args into a class/Struct and it can be reused in other places. 
- [ ] Add a member in migraphx' rocblas_gemm to store solution index. 
       Store best solution index if available otherwise default value (<=0) 
- [ ] Add `tune()` method in MIGraphX's  rocblas_gemm class, which would build rocBLAS args and would follow steps 1-3 above and return solution_index. Assert that the best solution is valid. 
  - [ ] How to Profile?
    - [ ] 	Directly run for loops  inside `tune()` for now, which should be simpler to implement. 
    - [ ] 	Later, Make use of `gpu-driver`.  Link `migraphx_gpu` to `gpu-driver` to call  into  that. 
    - [ ] 	Not  sure if we can directly supply json file, otherwise directly call into `time_op()`. May need to avoid calling into `finalize()` in that case. 
- [ ] Call into `tune()` during lowering for GPU if tuning is enabled. 
- [ ] Add `finalize()` method in rocblas_gemm which would  [validate](https://github.com/ROCmSoftwarePlatform/rocBLAS-internal/blob/53c8ce8d3eb2eee9c7ca6711522efbf882de1646/clients/samples/example_user_driven_tuning.cpp#L172) best solution again and  optionally call into [rocblas_initialize()](https://github.com/ROCmSoftwarePlatform/rocBLAS/blob/27a3475d8f3a6f9a78f6f06170b472e94c35a9ae/library/include/internal/rocblas-functions.h#L18262).  If validation fails, warn users and fallback to default solution (solution_index <= 0). 
- [ ] Since rocBLAS has this as BETA api, guard everything related to this using environment variable for now.
- [ ] Later when [--exhaustive-tune](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/pull/1519) is set in `migraphx-driver` also enable rocBLAS tune. 

Testing : 

- [ ] test if there are any noticeable performance gains after tuning
- [ ] Looks for incompatibilities in MXR file e.g. hardware being different, warning on rocblas-version mismatch.

**Comment by umangyadav** [comment]
@pfultz2 @bpickrel

**Comment by umangyadav** [comment]
Ideally, it would have been better if rocBLAS itself profiled each solution and provided best solution index like  MIOpen.

**Comment by pfultz2** [comment]
> rocBLAS function calls requires a long list of arguments to pass. Refactor current code such that, we encapsulate building all those args into a class/Struct and it can be reused in other places.

To be clear we should only be running the gemms in the `compute` method, but we definitely need something to help pass all these argument. I think a simple `pack` and then way to invoke the function with the pack plus other parameters:

```cpp
auto create_gemm_args(context& ctx, const std::vector<argument>& inputs)
{
    // Compute the gemm arguments and return a pack
    ...
    return pack(...);
}
// The version with just shapes will use null pointers for the buffers
auto create_gemm_args(context& ctx, const std::vector<shape>& inputs)
{
    // Compute the gemm arguments and return a pack
    ...
    return pack(...);
}
// This will replace the old `rocblas_invoke` function
template<class F, class Pack, class... Ts>
auto rocblas_invoke(F f, Pack p, Ts... xs)
{
    return p([=](auto... ws) {
        return f(ws..., xs...);
    });
}
```

And we can call it like this:

```cpp
auto args = create_gemm_args(ctx, inputs);
rocblas_int size = 0;
auto r = rocblas_invoke(&rocblas_gemm_ex_get_solutions, args, rocblas_gemm_flags_none, NULL, &size);
```

When we query the solutions we wont have gpu buffers(as those get allocated by `time_op`), so the overload to take shapes can just use null pointers(if this isn't accepted by rocblas API then we should file a defect).

The current `rocblas_invoke` function in migraphx was to handle an API change in rocblas, but that is for a very old version so we can remove that. 

> Add a member in migraphx' rocblas_gemm to store solution index.
> Store best solution index if available otherwise default value (<=0)

I was thinking we store as `optional<>`, but needs #1495.

> Directly run for loops inside tune() for now, which should be simpler to implement.

The simplest way is to just to do a for loop over each solution and call `time_op`:

```cpp
std::size_t tune(context& ctx, std::size_t n, const std::vector<shape>& inputs) const
{
    std::size_t r = 0;
    auto op = *this;
    double min_time = std::numerical_limits<double>::max();
    for(std::size_t i=0;i<n;i++)
    {
        op.solution = i;
        auto host_time = time_op(ctx, op, inputs, 10).first;
        if (host_time < min_time)
        {
            r = i;
            min_time = host_time;
        }
    }
    return r;
}
```

The `time_op` will take care of allocating gpu buffers. We use only the host time. The device time is only supported for kernels we launch, it is not supported for third-party libraries like rocblas.

> Later, Make use of gpu-driver. Link migraphx_gpu to gpu-driver to call into that.

`migraphx_gpu` should not depend on the `gpu-driver` that would create a circular dependency. Instead we should move the `time_op` function to `migraphx_gpu` library. 

> Call into tune() during lowering for GPU if tuning is enabled.

Actually, thinking about it more, its not a good idea to do this in lowering since the layout of the tensors haven't been decided yet. Since there is no workspace, we could probably just call `tune()` in `finalize`(instead of in `compile` and `compile_miopen` like what we do for convolution).

> Add finalize() method in rocblas_gemm which would [validate](https://github.com/ROCmSoftwarePlatform/rocBLAS-internal/blob/53c8ce8d3eb2eee9c7ca6711522efbf882de1646/clients/samples/example_user_driven_tuning.cpp#L172) best solution again and

How expensive is validation? We may want to only validate after tuning.

> optionally call into [rocblas_initialize()](https://github.com/ROCmSoftwarePlatform/rocBLAS/blob/27a3475d8f3a6f9a78f6f06170b472e94c35a9ae/library/include/internal/rocblas-functions.h#L18262). If validation fails, warn users and fallback to default solution (solution_index <= 0).

We should call `rocblas_initialize` in `get_rocblas` in the `context`.

> Since rocBLAS has this as BETA api, guard everything related to this using environment variable for now.

If beta means they may break the function signatures, then we may need a build flag for this, or some cmake checking if the API is available.

**Comment by umangyadav** [comment]
> Actually, thinking about it more, its not a good idea to do this in lowering since the layout of the tensors haven't been decided yet. Since there is no workspace, we could probably just call tune() in finalize(instead of in compile and compile_miopen like what we do for convolution).

Layout you mean `int8_x4_format` ? 

> How expensive is validation? We may want to only validate after tuning.

 Not sure, but it  is a good idea to validate if user is using rocblas's `.so` file not having a requested solver. This example has special flag `rocblas_gemm_flags_check_solution_index` for validation. So likely it is not too much expensive. 

If we move `tune()` to finalize, it would increase runtime for `finalize()` anyways. 

> If beta means they may break the function signatures, then we may need a build flag for this, or some cmake checking if the API is available. 

CMake check is good idea but also need `ENV` var to override that for now i guess.

**Comment by umangyadav** [comment]
> I was thinking we store as optional<>, but needs https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/pull/1495. 

We only need to store `solution_index` and we have default value for the same. I think It is fine to keep it Not optional.

**Comment by pfultz2** [comment]
> Layout you mean int8_x4_format ?

No, I mean like NHWC, but in the case of matrix I mean whether a matrix is transposed or not. 

> tune() during finalize(), we need to differentiate if finalize() is being called during compile or during de-serialization.

If `solution_index` is not set, and the `context` doesnt have `exhaustive-tune` set then we wont tune. However, we wont ever set `exhaustive-tune` during deserialization, so it wont be ran on untuned models either. 

> If we move tune() to finalize, it would increase runtime for finalize() anyways.

The concern is during `load` and not during `compile`, `tune()` should only be called during compile. Hopefully, its not too expensive. If it becomes too expensive then we should see if we can do a rocblas version check(using `rocblas_get_version_string`). 

> We only need to store solution_index and we have default value for the same. I think It is fine to keep it Not optional.

As long as rocblas has the default value documented, then that should be fine.

**Comment by umangyadav** [comment]
- [ ] Check for return status from rocblas, Currently, we are not doing any status check.

**Comment by umangyadav** [comment]
- [ ] Use HPL or some other initialization which would be more closer to real world data instead of random init for benchmarking as it can affect which solution is picked.

**Comment by umangyadav** [comment]
- Caching:  

- [ ] Currently, GEMM tunings is taking a long time for some of the models. There should be some mechanism for caching the results of tuning.  Right now it seems there is no such mechanism from rocBLAS.  We should request such a feature and on the side also implement caching on our side guarded by some CMake logic or ENV flag.

**Comment by bpickrel** [comment]
> > rocBLAS function calls requires a long list of arguments to pass. Refactor current code such that, we encapsulate building all those args into a class/Struct and it can be reused in other places.
> 
> To be clear we should only be running the gemms in the `compute` method, but we definitely need something to help pass all these argument. I think a simple `pack` and then way to invoke the function with the pack plus other parameters:
> 
> ```c++
> auto create_gemm_args(context& ctx, const std::vector<argument>& inputs)
> {

This is turning out not to be such an efficiency since different BLAS API calls take slightly different argument lists and so require different createXXX() methods, each with different pack... return types.
