### ISSUE TITLE
Update documentation about usage  of install_deps.cmake

### ISSUE THREAD

**Issue by umangyadav** [ROCmSoftwarePlatform/AMDMIGraphX#1568]
MIGraphX can make of `install_deps.cmake` to install dependencies as follows : 
`cmake -P install_deps.cmake --prefix /path/to/deps` 

This is not documented in README.md. 

Upon trying to use this way, it currently fails with parsing error for `zlib`.  It is incorrectly picking URL to fetch that package.

**Comment by pfultz2** [comment]
`install_deps.cmake` should just be removed. It was there only to help support backwards compatibility with older scripts that were building migraphx. Since its broken then there are probably no scripts using this anymore and should just be removed.
