### ISSUE TITLE
Add option to add target GFX arch in MIGraphX

### ISSUE THREAD

**Issue by umangyadav** [ROCmSoftwarePlatform/AMDMIGraphX#1583]
MIGraphX doesn't have a way to tell which gfx-arch to use right now (cross-compilation).  For the GPU target, it only accepts `gpu` as target string but not like `gfx90a`

**Comment by pfultz2** [comment]
The problem is that we run things on the GPU during compile, so performance can be affected.

**Comment by causten** [comment]
migraphx needs to stop using hip-config.cmake to determine current targets.  

- [ ]  Adjust code to only build for what is on the system.

**Comment by TedThemistokleous** [comment]
related to issues seen in #2201

**Comment by TedThemistokleous** [comment]
Moved this to @pfultz2 PR which handles error to specify GPU_TARGETS if HIP fails to specify.
