### ISSUE TITLE
Use `apt install` for half

### ISSUE THREAD

**Issue by umangyadav** [ROCmSoftwarePlatform/AMDMIGraphX#1584]
`half` is available through rocm. It can be removed from requirements.txt and can be installed and used similarly to MIOpen/rocBLAS as a dependency.

**Comment by causten** [comment]
add dependency to rbuild.ini to allow jenkins to work

**Comment by lakhinderwalia** [comment]
Had a brief discussion with @umangyadav. This change would break the (case of) automated dependency setup for https://github.com/ROCmSoftwarePlatform/AMDMIGraphX#use-cmake-to-build-migraphx.

Therefore, we shall just update the version dependency (for Half) from 5.4.2 to 5.6.
