### ISSUE TITLE
Unique Operator is not supported

### ISSUE THREAD

**Issue by causten** [ROCmSoftwarePlatform/AMDMIGraphX#1590]
Needed to support the bevdet.onnx model

BevDet model: bevdet.onnx

Error message:
terminate called after throwing an instance of 'migraphx::version_1::exception'
 what(): /workspace/AMDMIGraphX/src/onnx/onnx_parser.cpp:328: parse_graph: Unknown operator: Unique
Aborted (core dumped)

**Comment by lakhinderwalia** [comment]
Do we support these optional return values: https://numpy.org/doc/stable/reference/generated/numpy.unique.html

Referenced from here: https://onnx.ai/onnx/operators/onnx__Unique.html

**Comment by causten** [comment]
makes sense to support if possible

**Comment by lakhinderwalia** [comment]
This is the customer's model: http://mklnxpgk.amd.com/ModelZoo/UIF/1.2_dev-migraphx/
Its (first) `/Unique` operator's multiple outputs are being deployed in the model:
1.  Regular output `Y`, is fed to 4 Gather operators.
2. `inverse_indices` output to `/Unique_1` in this graph.

**Comment by lakhinderwalia** [comment]
This Bevdet model is not const foldable for its Unique Operator(s). Here are the traces out of Driver' read operation for bevdet.onnx (it has 2 unique operators):

`@989 = unique[axis=0,sorted=1](@988) -> [int64_type, {219648, 4}, {4, 1}, int64_type, {219648}, {1}, int64_type, {219648}, {1}, int64_type, {219648}, {1}], target_id=0
@990 = get_tuple_elem[index=0](@989) -> int64_type, {219648, 4}, {4, 1}, target_id=0
@991 = get_tuple_elem[index=1](@989) -> int64_type, {219648}, {1}, target_id=0
@992 = get_tuple_elem[index=2](@989) -> int64_type, {219648}, {1}, target_id=0
@993 = get_tuple_elem[index=3](@989) -> int64_type, {219648}, {1}, target_id=0

@1012 = unique[axis=0,sorted=1](@992) -> [int64_type, {219648}, {1}, int64_type, {219648}, {1}, int64_type, {219648}, {1}, int64_type, {219648}, {1}], target_id=0
@1013 = get_tuple_elem[index=0](@1012) -> int64_type, {219648}, {1}, target_id=0
@1014 = get_tuple_elem[index=1](@1012) -> int64_type, {219648}, {1}, target_id=0
@1015 = get_tuple_elem[index=2](@1012) -> int64_type, {219648}, {1}, target_id=0
@1016 = get_tuple_elem[index=3](@1012) -> int64_type, {219648}, {1}, target_id=0`
