### ISSUE TITLE
[RFC] Backend targets as plug-in shared objects

### ISSUE THREAD

**Issue by umangyadav** [ROCmSoftwarePlatform/AMDMIGraphX#1595]
### **Background:**

MIGraphX currently supports three different target backends e.g. CPU, GPU, and FPGA. In the future, it could potentially support more backends through different mechanisms. 
MIGraphX has a modular architecture and is built as a collection of shared libraries. 
•	`libmigraphx.so` provides core functionality and infrastructure for MIGraphX IR, interface with different backends and common IR passes. 
•	`libmigraphx_tf.so` provides functionality related to parsing TensorFlow/Protobuf models. 
•	`libmigraphx_onnx.so` provides functionality related to parsing onnx models. 
•	`libmigraphx_gpu.so`: GPU backend target and links to core `libmigraphx.so`. 
•	`libmigraphx_ref.so`: Ref target which provides gold standard CPU-based reference implementation to compare results against for correctness and verification. 
•	`libmigraphx_cpu.so`: CPU target that uses ZenDNN and links to core `libmigraphx.so`. 
•	`libmigraphx_fpga.so`: FPGA target 
•	`libmigraphx_c.so` is a separate C/C++ API library that external applications links against to make use of MIGraphX. C/C++ API library internally links to `libmigraphx.so`, `libmigraphx_tf/onnx`, and to all the target .so files.  

All backend target libraries links to `libmigraphx.so`. 

### **Packaging :** 

By default MIGraphX ships with only ref and GPU targets enabled. 
By default, MIGraphX is a non-relocatable package. But the probability is that it would change in the future. 
MIGraphX is available on Linux platforms and windows support is in development. 

### **Problem :** 

As the number of targets increases, the number of dependencies that it requires also increases. Currently, if any of the dependencies are not present for any of the targets then, MIGraphX would just fail to load.  For example, MIOpen is a dependency for GPU target. If MIOpen is not present then ideally MIGraphX should still be able to execute Ref target, but it fails to do so. 

MIGraphX in future would allow for multi-target execution. In such cases, it should have ability to scan for available backend targets on the machine and make them available for compilation. 

### **MIGraphX backend targets :**

All targets in MIGraphX implements a common [interface ](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/blob/97940f81f848b42775cacc7ea6a05f4c2c4efeed/src/include/migraphx/target.hpp#L51) that includes `get_passes()`, `name()`, `allocates()` etc.  

All backend targets are put into a registry of "type-erased target" when [MIGRAPHX_REGISTER_TARGET](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/blob/97940f81f848b42775cacc7ea6a05f4c2c4efeed/src/include/migraphx/register_target.hpp#L58) is invoked. This registration process happens by default when the backend library is loaded into memory. 

When the compilation is requested for a target, "type erased target" is fetched from registry and `get_passes()` is [called ](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/blob/97940f81f848b42775cacc7ea6a05f4c2c4efeed/src/program.cpp#L219)onto it.

### **Proposed Solution:** 

Use plug-ins. Dynamically Load target shared object libraries during runtime. This can be achieved by `dlopen` for the linux and `LoadLibraryW` on windows.  As any of the  backend library is loaded `REGISTER_TARGET` gets invoked and target becomes available for compilation automatically. 

### **Design considerations :** 

Path resolution: On the linux, CMake can set RPATH and things works out very well. But for the windows it is not straightforward. 

De-allocation: When any of the backend libraries are unloaded, make sure deallocation happens before unloading for all the objects managed by that backend library. 

Re-locatable package: If MIGraphX were to be shipped as a re-locatable package, how would that work out? 

C/C++ runtime libraries compatibility: Backend plug-ins should be compatible. e.g. libc++ v/s libstdc++. This wouldn't be an issue given how targets are designed in MIGraphX. 

Loading/Unloading of libraries: It can be managed by wrapper managed pointer. 

Shipping: Currently MIGraphX ships only for Ref and GPU targets. How that should be changed for plug-ins backends? 
Can we expect the users to provide `libmigraphx_xyz.so` and move it under `/opt/rocm/lib` or allow them to place it anywhere and ask them to set `LD_LIBRARY_PATH` ? 

Multi-target execution: How the compilation target should be specified for that ? e.g. target_name == "all" ? and it should load any available backend library? 

`dlopen` adds `libdl.so` as additional runtime dependency. 

cc : @hgaspar @pfultz2 @varunsh-xilinx @IncinX

**Comment by umangyadav** [comment]
https://github.com/apache/tvm/blob/main/src/runtime/dso_library.cc 

TVM has this interface for loading any modules.

**Comment by pfultz2** [comment]
> By default, MIGraphX is a non-relocatable package.

The package can be moved to a different directory, but it is not relocatable with RPM because the install prefix is an absolute path(this is mainly a rocm-cmake issue). I am not sure how this is relevant to this issue here.

> In such cases, it should have ability to scan for available backend targets on the machine and make them available for compilation.

The user should always explicitly say which targets it wants to use when compiling. Even if the dependencies are available the device still may not be available.

**Comment by pfultz2** [comment]
In our API lib(ie `libmigraphx_c.so`) we can lazy load backends as `lib_migraphx_${target}.so`:

```cpp
target get_target(const std::string& name)
{ 
    if (not contains(get_targets(), name))
    {
        auto lib = dynamic_loader("libmigraphx_" + name + ".so");
        // Store the library somehow to keep lifetime alive for rest of the process
        store_backend(lib);
    }
    return make_target(name);
}
```

This will avoid the issue with loading in so many dependencies.

> C/C++ runtime libraries compatibility: Backend plug-ins should be compatible. e.g. libc++ v/s libstdc++. This wouldn't be an issue given how targets are designed in MIGraphX.

There is no C compatibility and users will need to use the same c++ runtime and c++ version as migraphx. 

> Loading/Unloading of libraries: It can be managed by wrapper managed pointer.

We have `dynamic_loader` to manage libraries.

> Shipping: Currently MIGraphX ships only for Ref and GPU targets. How that should be changed for plug-ins backends?
Can we expect the users to provide libmigraphx_xyz.so and move it under /opt/rocm/lib or allow them to place it anywhere and ask them to set LD_LIBRARY_PATH ?

For user backends, the user will either do:

* Put a `libmigraphx_${target}.so` in the library path so it will automatically load
* Do `dlopen` or `LoadLibrary` on the backend
* Link the backend with their application

> Multi-target execution: How the compilation target should be specified for that ? e.g. target_name == "all" ? and it should load any available backend library?

There is no `all` target. The user always needs to explicitly ask for the targets they want to compile for.

Other considerations, we need to update the version symbols so users wont use the backends across different versions of migraphx(they should rebuild their backend for a different version of migraphx). We have `MIGRAPHX_INLINE_NS` to version the symbols, we just need to update it to automatically use the migraphx version.

**Comment by umangyadav** [comment]
> In our API lib(ie libmigraphx_c.so) we can lazy load backends as lib_migraphx_${target}.so:

 Would it be better if we were to do that inside `libmigraphx_so.` ? 

```
std::unordered_map<std::string, dynamic_loader>& lib_loader_map()
{
    static std::unordered_map<std::string, dynamic_loader> loader;
    return loader;
}

target make_target(const std::string& name)
{
    if(not contains(lib_loader_map(), name))
    {
        auto target_lib_loader = dynamic_loader("libmigraphx_" + name + ".so");
        // print(get_load_error_message());
        lib_loader_map()[name] = target_lib_loader;
    }
    const auto it = target_map().find(name);
    if(it == target_map().end())
    {
        MIGRAPHX_THROW("Requested target '" + name + "' is not enabled or not supported");
    }
    return it->second;
}
```
