### ISSUE TITLE
ResNet50 accuracy

### ISSUE THREAD

**Issue by attila-dusnoki-htec** [ROCmSoftwarePlatform/AMDMIGraphX#1746]
There is a accuracy issue regarding ResNet50.

MIGraphX version: 2bebf64dc993b809801cf9e2d93c62ff5b54b991

Model link: https://zenodo.org/record/2592612/files/resnet50_v1.onnx

Dataset: https://www.image-net.org/download.php

The expected accuracy should be `76.46%`.

With FP32:
```bash
accuracy=76.456%, good=38228, total=50000
```

With FP16:
```bash
accuracy=75.456%, good=37728, total=50000
```

Difference file:  [resnet_fp16_fp32_diff.log](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/files/11421457/resnet_fp16_fp32_diff.log)

Left column: fp16 | Right column: fp32
The `*` at the end means it is different from the expected.

Snippet:

```bash
# fp16 incorrect, fp32 correct
ILSVRC2012_val_00038032.JPEG, expected: 750, found 36 *	      |	ILSVRC2012_val_00038032.JPEG, expected: 750, found 750 
# fp16 correct, fp32 incorrect
ILSVRC2012_val_00001982.JPEG, expected: 650, found 650 	      |	ILSVRC2012_val_00001982.JPEG, expected: 650, found 546 *
# fp16 incorrect, fp32 incorrect, but both different
ILSVRC2012_val_00003249.JPEG, expected: 502, found 463 *      |	ILSVRC2012_val_00003249.JPEG, expected: 502, found 104 *

# Mapping
36: 'terrapin'
750: 'quilt, comforter, comfort, puff'

650: 'microphone, mike'
546: 'electric guitar'

463: 'bucket, pail'
104: 'wallaby, brush kangaroo'
502: 'clog, geta, patten, sabot'
```

Note: the images require [preprocessing](https://github.com/mlcommons/inference/blob/master/vision/classification_and_detection/python/dataset.py#L168-L184).

These are only the labels, the scores are not used in the scripts. I realize that those numbers would also be important, so I can update this issue with that info later if needed.

The expected accuracy would be better: `Max 99% of 76.46% (75,6954%)`.

**Comment by kahmed10** [comment]
Can we see the difference in scores? Maybe top5 results. Especially where fp16 is incorrect but fp32 is correct.

**Comment by gyulaz-htec** [comment]
@kahmed10 I've collected the top5 scores and extended the previous diff file:
[resnet_fp16_fp32_diff.log](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/files/11506182/resnet_fp16_fp32_diff.log) 
Is there anything else we can provide?

**Comment by gyulaz-htec** [comment]
Also I've run fp16 with `MIOPEN_DEBUG_CONV_WINOGRAD=0` and only two more sample passes with that setting.
FP16 accuracy with `MIOPEN_DEBUG_CONV_WINOGRAD=0`:
`accuracy=75.460%, good=37730, total=50000`
previous FP16 accuracy:
`accuracy=76.456%, good=38228, total=50000`

**Comment by umangyadav** [comment]
@gyulaz-htec Can you share script that you used to run inference and calculate accuracy on entire model ? 

also how are you generating FP16 model ? is it by passing `--fp16` flag to the `migraphx-driver` ?
