### ISSUE TITLE
Update builtin "@return" to return correct shape

### ISSUE THREAD

**Issue by umangyadav** [ROCmSoftwarePlatform/AMDMIGraphX#1767]
https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/blob/0e6ee3f7ff7880e9e65b84fbceed8686e426bc8a/src/include/migraphx/builtin.hpp#L93

It returns default constructed shape all the time.  

In debugging JIT kernels, MIGraphX prints type of the return instruction in some places which comes out to be "float" each time regardless of input data type because `builtin::return` returns the default shape.

**Comment by lakhinderwalia** [comment]
Builtin "@return" now handles shape::tuple_type correctly. Test cases added to check empty, half_type and tuple_type.
