### ISSUE TITLE
investigate Benchmarks failures TIMM

### ISSUE THREAD

**Issue by causten** [ROCmSoftwarePlatform/AMDMIGraphX#1822]
Collect the error logs

**Comment by TedThemistokleous** [comment]
error related to changes with respect to reshape right now

Current changes to solve these issues is found at : trace_simplify_alg_matches

**Comment by TedThemistokleous** [comment]
related to this effort is #1677  after with speaking with @pfultz2 and doing further debug. It looks like we need to add reshape_copy type of operator to handle some of the edge cases when we hit a reshape operator during the inner_broadcast matcher.

@shivadbhavsar  I heard you started something like this earlier. How far did you get? Is there anything we can reuse? 

from my understanding it looks like we have to do the following

- [ ] reshape becomes "lazy" reshape op between simple inner_broadcasts
- [ ] reshape_copy to handle more complex shapes that we can't perform without modifying memory on compile
- [ ] update unit tests for reshape
- [ ] add unit tests for reshape_copy

@pfultz2  let me know if I've missed anything.

**Comment by TedThemistokleous** [comment]
Current branch of work is in modify_reshapes_pre_1751. needs to be cleaned up but having issue with populating dims() for new reshape_lazy op during lowering. 

@pfultz2

**Comment by TedThemistokleous** [comment]
This is just in review still no more work needed
