### ISSUE TITLE
Add split operator

### ISSUE THREAD

**Issue by mei-ye** [ROCmSoftwarePlatform/AMDMIGraphX#184]
https://www.tensorflow.org/api_docs/python/tf/split
Split is also need to dis-aggregate horizontally-fused intermediate results.
Though there are two approaches for better performance:
1. MIOpen supports fusion of splits with other operators (e.g., conv_bias_relu).
2. MIOpen supports channel-first tensor format which avoids the need for doing split.

**Comment by pfultz2** [comment]
How is split different than the slice operator?

**Comment by mei-ye** [comment]
"split" returns multiple slices in one kernel call.   Unless we support multiple return values for one instruction, we might as well return multiple slices in one big array.   The implementation may or may not use the slice operator implementation. 

Parameters:  
axis:  axis to be splitted.
size: an array of integers specifying dimensions after the split.

**Comment by pfultz2** [comment]
Or we can just insert multiple slices since those dont require any kernel to be ran.

**Comment by mei-ye** [comment]
Existing implementation of "slice" operators seems to assume that data layout in a slice is always contiguous.   I do not know what our "slice" operator is used for.   For the split operator, if the axis to split is not the 1st one, data layout is not contiguous.

**Comment by mei-ye** [comment]
in test\gpu\miopen.cpp,  "slice" and "concat" are compared with cpu implementation, shouldn't they be compared to expected results?   If both cpu and gpu use the same algorithm,  but the algorithm is wrong.  This will still verify that it passes. 

Do we have a documentation on expected behaviors of our operators?

Existing implementation for both "slice" and "concat" is quite different from my understanding.
My understanding is like this:
https://eli.thegreenplace.net/2015/memory-layout-of-multi-dimensional-arrays/

**Comment by scxiao** [comment]
For "should not they be compared to expected results?"
In my understanding, tests in miopen.cpp is to ensure CPU implementation and GPU implementation generate the same results. Our CPU and GPU implementations are supposed to use the same algorithm, but they are two different implementations, which can generate different results if one or both are wrong. As for compared to expected results, that is in the cpu test/cpu_ops_test.cpp file, in which outputs are compared to expected results."

As for documentation, they are two sources. One is the onnx operator webpage; the other is the numpy index/slice at https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.indexing.html
it is supposed to generate the same results as numpy index/slice.

**Comment by mei-ye** [comment]
Shucai,  thanks for the pointer, I now see your cpu_ops_test.  I followed the example to write some tests to help me to understand its behavior,  It looks correct so far.  So,  I might be able to use slice operator instead of using split.

**Comment by mei-ye** [comment]
I was a bit puzzled on how the contiguous layout is guaranteed since "slice" only returns a pointer.
I found that a "contiguous" instruction is inserted after each "slice" instruction which does the job.  For the gpu target, this turns into a kernel call in "nary_nonstandard".

So back to Paul's initial question, can we use "splice" instead of "split" instead?
Yes, we can,.  But we will need multiple "splice" instructions, each of them is followed by "gpu::contiguous", which introduces multiple kernel calls.

My conclusion is:  we need a split operation, which unified multiple slices and "gpu::contiguous" in one kernel call.

**Comment by pfultz2** [comment]
The "contiguous" operators are removed if the operators support non-standard layouts. So if these are feed into operators such as `add` or `relu` then "contigous" will be removed. 

If we want to do a one time contiguous across several slices, we can use "concat" for that. We will need to do another slice after the concat but that second slice will be packed and contiguous.

**Comment by pfultz2** [comment]
Even better, we could have a pass that finds several contiguous operators and fuses them into concat, which will fuse contiguous for more than just slices.

Although, in this case we will need to optimize concat as it currently runs several kernels instead of one.

**Comment by mei-ye** [comment]
A "split" algorithm that does not rely on "contiguous" will be preferable.  
Input: one array
Output: one array

Calculate the mapping of input index and output index, and copy the data accordingly,

**Comment by mei-ye** [comment]
Also, it is better if MIOpen can support the fusion of split.  When MIOpen writes the result of "conv_bias_relu", it can write to the "split" output directly.

**Comment by mvermeulen** [comment]
My two cents:
- There is an issue of ONNX operators as well as internal IR.  I think it makes sense to accept the ONNX split operator.
- Next question is in regard to our internal IR.  I would bias towards introducing a split operator.
- Separate from this is the overall aspect of "layout planning"; I think here it makes sense to understand not just for split, but also other operators that don't have to change layouts (e.g. reshape) what type of optimization we do and how it is organized into passes.  I'd rather see that described as whole rather than just focused on split by itself.

**Comment by scxiao** [comment]
Just took a quick look, the following are our operators that may need contiguous inserted after.
transpose
squeeze
unsqueeze
reshape
as_shape
identity
flatten
broadcast
multibroadcast
scalar

**Comment by pfultz2** [comment]
>     * There is an issue of ONNX operators as well as internal IR.  I think it makes sense to accept the ONNX split operator.

The split operator uses multiple outputs which we dont support. Instead, we would just map it to multiple slice operators.

>     * Next question is in regard to our internal IR.  I would bias towards introducing a split operator.

I dont think we can support a full split in our IR. We can concat the splits in a single tensor if each split has the same tensor shape, but that is not always the case:

```python
node = onnx.helper.make_node(
    'Split',
    inputs=['input'],
    outputs=['output_1', 'output_2'],
    axis=1,
    split=[2, 4]
)

expected_outputs = [np.array([[1., 2.], [7., 8.]]).astype(np.float32),
                    np.array([[3., 4., 5., 6.], [9., 10., 11., 12.]]).astype(np.float32)]

expect(node, inputs=[input], outputs=[y for y in expected_outputs], name='test_split_variable_parts_2d')
```

>     * I'd rather see that described as whole rather than just focused on split by itself.

Most of the operators that just change the shape are done in a target-independent manner, since all they really do is modify the shape of the tensor. There are only a few that require implementations on the gpu: contiguous, concat, and gather, but we try to keep those operators to a minimum.

**Comment by mei-ye** [comment]
We currently do not support multiple results in one instruction, which might need a change if more cases  like this are encountered in the future.   As of now,  we can return all splitted tensors in one flattened array.  The consumers of split can get the data by indexing into this big array using "base + offset".  We have "load" instruction for this purpose.

"contiguous" is essentially a "transpose".  Using "transpose" to do the extraction of  slices is easier to understand and code.   But it is expensive.    The question is whether we can find an algorithm to map the indexes of input/output array and to move the data in a single kernel that is efficient to run on GPU.  I am thinking along this line.

**Comment by pfultz2** [comment]
> As of now, we can return all splitted tensors in one flattened array. The consumers of split can get the data by indexing into this big array using "base + offset". We have "load" instruction for this purpose.

Ah yes, in this case, "load" will work and we dont need to call to the contiguous operator.

> Using "transpose" to do the extraction of slices is easier to understand and code. But it is expensive.

If the consumers need contiguous inputs, then we need to do this "transpose", unfortunately. As an optimization, we could batch process several contiguous operators(which is essentially a concat operator).

**Comment by mei-ye** [comment]
I think I know how to map the index between input and output, which can be computed at compilation time and passed to kernel.
Borrowing OCL syntax, (will be ported to HIP),  the kernel declaration will be like:
// out[index_map[i]] = in[i]
__kernel void vector_copy(__global const float * restrict in,
                                          __global float* restrict out,
                                           __global const int* index_map,
                                          const int N)

**Comment by scxiao** [comment]
> We currently do not support multiple results in one instruction, which might need a change if more cases like this are encountered in the future. 

One other case is the RNN operators. which can generate two or three results. We have a workaround to get the result we want, but we still cannot not output multiple results simultaneously. 
If we met more cases like this, we had better change earlier.

**Comment by scxiao** [comment]
> > We currently do not support multiple results in one instruction, which might need a change if more cases like this are encountered in the future.
> 
> One other case is the RNN operators. which can generate two or three results. We have a workaround to get the result we want, but we still cannot not output multiple results simultaneously.
> If we met more cases like this, we had better change earlier.

Should we create a new issue to track the multiple results?

**Comment by mvermeulen** [comment]
Yes, please open a new issue.

**Comment by mvermeulen** [comment]
No change.
