### ISSUE TITLE
[rocMLIR] Threading/registration cleanup

### ISSUE THREAD

**Issue by krzysz00** [ROCmSoftwarePlatform/AMDMIGraphX#1861]
I have investigated how to update MIGraphX's handling of initializing/calling rocMLIR to make it better conform to recommended practice from upstream.

A prerequisite for such changes to MIGraphX, which give us a better chance of making multithreaded MLIR work right, is https://github.com/ROCmSoftwarePlatform/rocMLIR-internal/issues/973 , where the MLIR C API needs to be extended.

However, after that is done, the setup should be as follows:
1. Create, in a thread-safe way (`call_once`) a `MlirDialectRegistry` and what I'm going to call a `MlirLlvmThreadPool` and keep these around. While you're there, call `registerRocMLIRPasses()` - you need that to initialize stuff like the LLVM backend (indirectly) and that function isn't known to be thread-safe right now (though some upstream changes might fix that Eventually)
2. You'll be doing
```
MlirContext ctx = MlirCreateContextWithOptions(theRegistry, false);
mlirContextSetThreadPool(ctx, theThreadPool);
mlirContextLoadAllAvailableDialects(ctx);
```
You don't need to destroy the registry or to set the allow unregistered dialects flag.

This can be done independently of removing the locks.

You'll want to create a context once for each distinct module you're sending in.

**Comment by krzysz00** [comment]
This is now https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/pull/1867

**Comment by aserio** [comment]
Work is now complete
