### ISSUE TITLE
ONNX parsing of inceptionv3 introduces extraneous identity operator (dropout issue?)

### ISSUE THREAD

**Issue by mvermeulen** [ROCmSoftwarePlatform/AMDMIGraphX#190]
Following are the last instructions listed by read_onnx for inceptionv3i1.onnx:
```
@791 = convolution[padding=0, 0,stride=1, 1,dilation=1, 1,padding_mode=0,group=1](@790,@6) -> float_type, {1, 192, 8, 8}, {12288, 64, 8, 1}
@792 = batch_norm_inference[epsilon=0.001,momentum=0.9,bn_mode=1](@791,@5,@4,@3,@2) -> float_type, {1, 192, 8, 8}, {12288, 64, 8, 1}
@793 = relu(@792) -> float_type, {1, 192, 8, 8}, {12288, 64, 8, 1}
@794 = concat(@766,@776,@789,@793) -> float_type, {1, 2048, 8, 8}, {131072, 64, 8, 1}
@795 = pooling[mode=a, v, e, r, a, g, e,padding=0, 0,padding_mode=0, 0,stride=8, 8,lengths=8, 8](@794) -> float_type, {1, 2048, 1, 1}, {2048, 1, 1, 1}
@796 = identity(@795) -> float_type, {1, 2048, 1, 1}, {2048, 1, 1, 1}
@797 = flatten[axis=1](@796) -> float_type, {1, 2048}, {2048, 1}
@798 = transpose[dims=1, 0](@1) -> float_type, {2048, 1000}, {1, 2048}
@799 = dot[alpha=1,beta=0](@797,@798) -> float_type, {1, 1000}, {1000, 1}
@800 = multibroadcast[output_lens=1, 1000](@799) -> float_type, {1, 1000}, {1000, 1}
@801 = multibroadcast[output_lens=1, 1000](@0) -> float_type, {1, 1000}, {0, 1}
@802 = add(@800,@801) -> float_type, {1, 1000}, {1000, 1}
@803 = identity(@795) -> float_type, {1, 2048, 1, 1}, {2048, 1, 1, 1}
```
Of particular interest is node @803, with two items to note:
1. When printing the ONNX file, the overall shape of the output node is float_type, {1,1000} not this particular identity node.
2. It has duplicate inputs and shapes as node @796 which seems to come from a Dropout operator in the ONNX parser.

Overall, this seems as if the parsing of dropout to turn into an identity might somehow create this extra node as well?

**Comment by scxiao** [comment]
Looks like the last identity operator comes from the following code 

instruction_ref program::replace_instruction(instruction_ref ins, instruction_ref rep) {
    assert(has_instruction(ins));
    assert(has_instruction(rep));
    assert(ins != rep);
    if(ins == std::prev(this->end()))    {
        return replace_instruction(ins, op::identity{}, rep);
    }
................
can you post the last few operators of the onnx file? From that, maybe we can know why the replace_instruction is called.

**Comment by mvermeulen** [comment]
Here is the output I see from the following python program
```
#
import onnx
import sys
if len(sys.argv) == 2:
    model = onnx.load(sys.argv[1])
    print(model)
else:
    print('Usage: python3 print_onnx.py <filename>')
```
When I run this on the onnx file and then do an
```
egrep \(node\|op_type\|input\|output\)
```
I get the following file of operations listed.
[grep_inceptionv3i1.txt](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/files/2902863/grep_inceptionv3i1.txt)

The last ops in this file are as follows
```
   op_type: "BatchNormalization"
    op_type: "Relu"
    op_type: "Concat"
    op_type: "AveragePool"
    op_type: "Dropout"
    op_type: "Flatten"
    op_type: "Gemm"
```

**Comment by pfultz2** [comment]
There are two places where identity operators are added for inception. One is for dropout and another is when we remove concat.

**Comment by mvermeulen** [comment]
Fixed.
