### ISSUE TITLE
support multiple results in one instruction

### ISSUE THREAD

**Issue by scxiao** [ROCmSoftwarePlatform/AMDMIGraphX#191]
> > We currently do not support multiple results in one instruction, which might need a change if more cases like this are encountered in the future.
> 
> One other case is the RNN operators. which can generate two or three results. We have a workaround to get the result we want, but we still cannot not output multiple results simultaneously.
> If we met more cases like this, we had better change earlier.

Should we create a new issue to track the multiple results?

_Originally posted by @scxiao in https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/issues/184#issuecomment-467894855_

**Comment by mvermeulen** [comment]
Need to support the seq2seq example, may not need the general case yet.

**Comment by scxiao** [comment]
Created another issue #205 to track the program multiple outputs.

**Comment by kahmed10** [comment]
@scxiao implemented?

**Comment by mvermeulen** [comment]
Implemented.
