### ISSUE TITLE
missing "convolution + add_relu" fusion

### ISSUE THREAD

**Issue by mei-ye** [ROCmSoftwarePlatform/AMDMIGraphX#192]
inception v3 model has many "convolution + add_relu" patterns (about 20) that are not vertically fused.   
Below is snippet of dump:

@569 = gpu::convolution[padding=0, 0,stride=1, 1,dilation=1, 1,padding_mode=0,group=1](@566,@359,@567,@568) -> float_type, {1, 192, 17, 17}, {55488, 289, 17, 1}
.....
@573 = hip::add_relu(@569,@570,@572) -> float_type, {1, 192, 17, 17}, {55488, 289, 17, 1}
....
@945 = gpu::convolution[padding=1, 0,stride=1, 1,dilation=1, 1,padding_mode=0,group=1](@935,@243,@943,@944) -> float_type, {1, 384, 8, 8}, {24576, 64, 8, 1}
.....
@948 = hip::add_relu(@945,@946,@947) -> float_type, {1, 384, 8, 8}, {24576, 64, 8, 1}

**Comment by pfultz2** [comment]
We have some heuristics [here](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/blob/develop/src/targets/gpu/fuse_ops.cpp#L143) to skip miopen fusions when channel sizes are large or winograd is being used because miopen fusion is slower than doing it separately.

**Comment by kahmed10** [comment]
@pfultz2 resolved?

**Comment by mvermeulen** [comment]
Close no change.
