### ISSUE TITLE
Why do you need the eliminate_pad and insert_pad operations?

### ISSUE THREAD

**Issue by liucong521** [ROCmSoftwarePlatform/AMDMIGraphX#1968]
When I test the yolov3 mode, when I find that there is a pad+pooling combination in the model, the pass of eliminate_pad and insert_pad will be executed, the padded value will be deleted, the padded value will be restored to the minimum value, and the value will be input to max_pooling. Why does this transformation need to be done?

I want to know why do this? The problem with the pooling operator?

**Comment by kahmed10** [comment]
There is a limitation in MIOpen where pooling must be symmetrical. We minimize the new pad operator by calculating the maximum padding which would still be symmetrical and set that as an attribute for the pooling operator.
