### ISSUE TITLE
post message when mlir misses a group convolution

### ISSUE THREAD

**Issue by causten** [ROCmSoftwarePlatform/AMDMIGraphX#1978]

**Comment by kahmed10** [comment]
I was able to confirm resnext models are using convolutions with group=64.

**Comment by kahmed10** [comment]
https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/tree/mlir_gconv_msg if needed for testing other models.

**Comment by jerryyin** [comment]
@yiqian1 Has taken care of running this through @causten's model's list and figured only limited models have group conv2d

https://github.com/ROCmSoftwarePlatform/rocMLIR-internal/issues/1043#issuecomment-1702154515
