### ISSUE TITLE
LRN rewrite to bias/activation

### ISSUE THREAD

**Issue by scxiao** [ROCmSoftwarePlatform/AMDMIGraphX#204]

**Comment by scxiao** [comment]
After an initial investigation, the LRN cannot be rewritten in the same way we did for the batch normalization. For this issue, we will untag it to a specific release. If someone complains about it in the future, we will revisit it.

**Comment by scxiao** [comment]
Maybe we can add a parallel reduce operator, then we can rewrite this operator and achieve some performance improvement.

**Comment by scxiao** [comment]
Looked into the algorithm for LRN again, the following is the formula:

```
a) square_sum[n, c, d1, ..., dk] = sum(X[n, i, d1, ..., dk] ^ 2), where max(0, c - floor((size - 1) / 2)) <= i <= min(C - 1, c + ceil((size - 1) / 2)).

b) Y[n, c, d1, ..., dk] = X[n, c, d1, ..., dk] / (bias + alpha / size * square_sum[n, c, d1, ..., dk] ) ^ beta
```

A few thoughts:
1) LRN does the reduce of elements along the c axis as in equation a), and all elements with the same c index share the same reduce value, but different c indices need different reduce ops. That means, we need "C" number of reduces before we can do the computation in equation b).
2) The reduce algorithm we implemented works well for reduction along the last dimension, but the c dim here is not the last, and the performance is not expected to be good. The reason is reduction along non-last dim will cause additional useless memory load. 
3) Of course, we can wrote a kernel to do all reduces, then do equation b).

**Comment by mvermeulen** [comment]
Will not fix.
