### ISSUE TITLE
Add batch contiguous support

### ISSUE THREAD

**Issue by mei-ye** [ROCmSoftwarePlatform/AMDMIGraphX#207]
According to our discussion on March 11,  Paul agrees to support a "batch_contiguous" operator that takes multiple slices as input and produces either a single or multiple outputs.  Each of the outputs has a packed contiguous memory layout.   Input slices have no logical relationship to each other.  For GPU operator,  the algorithm must use only one kernel call.

**Comment by mvermeulen** [comment]
No change.
