### ISSUE TITLE
Investigate DETR model failure with latest develop branch

### ISSUE THREAD

**Issue by umangyadav** [ROCmSoftwarePlatform/AMDMIGraphX#2137]
Detr model from UIF was working until 
master branch revision: 1354c869b41e3e60d6477613e91575dc3933e7d8
but with the latest develop branch, it is running into  Following error : 

Compiling ...
Reading:  detr_r50_fp32.onnx
terminate called after throwing an instance of 'migraphx::version_2_7_0::exception'
  what():  /home/umayadav/repo/AMDMIGraphX/src/targets/gpu/gemm_impl.cpp:60: blas_shape: GPU_GEMM: needs to have one matrix stride as 1

**Comment by umangyadav** [comment]
Detr model is failing because it has this pattern: 

transpose --> contiguous --> preadd_layernorm --> add --> gemm. 

Before this https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/pull/2071, 

since `preadd_layernorm` does not have module inputs, using input `mods` caused `try_compute_shape` to return false and it didn't remove `contiguous`. 

But after #2071 it uses `output->module_inputs()` and then, `add` being a pointwise binary operator can take non-standard shape and outputs standard shapes, and therefore `try_compute_shape()` returns [true ](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/blob/f5da3bb258a6d67421d9a855e6a4eda3c406ed1c/src/eliminate_contiguous.cpp#L57) and eliminates the `contiguous`. 

But then `gemm` receives transposed input shape which doesn't have a stride of 1 in the last two dimensions and it fails with 
what(): /home/umayadav/repo/AMDMIGraphX/src/targets/gpu/gemm_impl.cpp:60: blas_shape: GPU_GEMM: needs to have one matrix stride as 1

**Comment by pfultz2** [comment]
So we start with:

transpose --> contiguous --> preadd_layernorm --> add --> gemm.

And then eliminate_contiguous give us:

transpose  --> preadd_layernorm --> add --> gemm.

But the output of `add` is not transposed?

Then we fuse it to this:

transpose  --> preadd_layernorm_add  --> gemm.

And then the output of `preadd_layernorm_add` is transposed?

**Comment by umangyadav** [comment]
> And then the output of preadd_layernorm_add is transposed? 

yes
