### ISSUE TITLE
Upgrade CI to 5.7.0

### ISSUE THREAD

**Issue by causten** [ROCmSoftwarePlatform/AMDMIGraphX#2200]
ROCM 5.7 just released

- [x] update all Dockerfiles with 5.7
- [x] Update CI Performance checks to 5.7
- [x] Update CI Accuracy checks to 5.7

**Comment by TedThemistokleous** [comment]
@causten @pfultz2 

I've updated changelog but also noticed that we're using half from 5.6 so Ive upgraded that as well.

**Comment by TedThemistokleous** [comment]
Took this on mid sprint (19). Currently in review
