### ISSUE TITLE
Figure out why AttentionBatch1_Float16 fails ORT CI

### ISSUE THREAD

**Issue by TedThemistokleous** [ROCmSoftwarePlatform/AMDMIGraphX#2228]
This test is randomly failing/passing in CI without any sense.

Current PR from Chris disables this #2226 as a work around right now

Find the root cause and determine why things are failing/not failing.

**Comment by causten** [comment]
https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/pull/2226 didn't solve the problem.  The failure occurred with another test just after.

**Comment by TedThemistokleous** [comment]
@causten guessing we can close this out due to the change from no more Vega for those tests?

**Comment by TedThemistokleous** [comment]
Closing this out since I havent seen the onnx issue again
