### ISSUE TITLE
In broadcast operator, change the broadcast_shape (shape type) to broadcast_len 

### ISSUE THREAD

**Issue by scxiao** [ROCmSoftwarePlatform/AMDMIGraphX#237]
@mei-ye commented on this pull request.
I discovered yesterday that broadcast operator has a broadcast_shape field.
If you change instruction's result shape, this field remains unchanged and so becomes obsoleted.
You can write a test case of adding a literal instruction and feed it into a broadcast. You could run into program validation failure. Any attempt to retype instruction could run into the same failure.

I checked the implementation, only the lens() of the shape is used, so maybe we can change the 
shape broadcast_shape to std::vector<std::size_t> broadcast_lens to avoid the above misrepresentation problem.

**Comment by mei-ye** [comment]
I see,  so your change is likely not going to trigger the assertion in broadcast.

**Comment by scxiao** [comment]
code merged in, so close it.
