### ISSUE TITLE
bidaf model fails to load in MIGraphX

### ISSUE THREAD

**Issue by mvermeulen** [ROCmSoftwarePlatform/AMDMIGraphX#271]
The following model can be found at - https://github.com/onnx/models/tree/master/bidaf

Reading this into MIGraphX results in the following error
```
mev@chilecito:~/source/AMDMIGraphX/build/src/onnx$ ./read_onnx /home/mev/source/migraphx_sample/onnx/bidaf.onnx 
[libprotobuf INFO google/protobuf/io/coded_stream.cc:610] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:81] The total number of bytes read was 43522228
terminate called after throwing an instance of 'std::out_of_range'
  what():  _Map_base::at
Aborted (core dumped)
```

As best I can tell, it was exported from CNTK and uses the following ops
```
	op    : Abs
	op    : Add
	op    : ArgMax
	op    : Cast
	op    : CategoryMapper
	op    : Ceil
	op    : Clip
	op    : Compress
	op    : Concat
	op    : ConstantOfShape
	op    : Conv
	op    : Dropout
	op    : Gather
	op    : Hardmax
	op    : Log
	op    : LSTM
	op    : MatMul
	op    : Mul
	op    : ReduceMax
	op    : ReduceSum
	op    : Relu
	op    : Reshape
	op    : Scan
	op    : Shape
	op    : Sigmoid
	op    : Slice
	op    : Softmax
	op    : Squeeze
	op    : Sub
	op    : Sum
	op    : Transpose
	op    : Unsqueeze
```

**Comment by scxiao** [comment]
We need the following operators to support this model (highlighted):
	op    : Abs
	op    : Add
	**op    : ArgMax**
	**op    : Cast**
	**op    : CategoryMapper**
	**op    : Ceil**
	op    : Clip
	**op    : Compress**
	op    : Concat
	op    : ConstantOfShape
	op    : Conv
	op    : Dropout
	op    : Gather
	**op    : Hardmax**
	op    : Log
	op    : LSTM
	op    : MatMul
	op    : Mul
	**op    : ReduceMax**
	**op    : ReduceSum**
	op    : Relu
	op    : Reshape
	**op    : Scan**
	op    : Shape
	op    : Sigmoid
	op    : Slice
	op    : Softmax
	op    : Squeeze
	op    : Sub
	**op    : Sum**
	op    : Transpose
	op    : Unsqueeze

**Comment by mvermeulen** [comment]
will not fix.
