### ISSUE TITLE
PyTorch examples/word_language_model (LSTM) not properly read

### ISSUE THREAD

**Issue by mvermeulen** [ROCmSoftwarePlatform/AMDMIGraphX#272]
PyTorch has an Recurrent Neural Network example that is easy to export to ONNX using the procedure as follows:
```
prompt% git clone https://github.com/pytorch/examples
prompt% cd word_language_model
prompt% python3 main.py --epochs 1 --onnx-export=wlanguage.onnx
```
Multiple options are available to this script, e.g.
- train for more epochs to get better trained model
- model=GRU
- batch_size

With the default options listed above, I try reading in the ONNX file with read_onnx and get an ONNX file that has "undefined" operators as inputs for LSTM  see "@44", "@47", "@72", "@75"
[wlanguage_migraphx.txt](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/files/3287144/wlanguage_migraphx.txt)

An additional item to note is this particular graph seems to have two inputs "@param:1" and "@param:2".  It also seems to create two outputs where "@99" comes from one of the lstm and "@100" comes from the other one.

**Comment by mvermeulen** [comment]
For completeness, I used all four model options
```
python3 main.py --epochs 1 --model=GRU --onnx-export=wlang_gru.onnx
python3 main.py --epochs 1 --model=LSTM --onnx-export=wlang_lstm.onnx
python3 main.py --epochs 1 --model=RNN_TANH --onnx-export=wlang_rnn_tanh.onnx
python3 main.py --epochs 1 --model=RNN_RELU --onnx-export=wlang_rnn_relu.onnx
```
Both versions the wlang_rnn_tanh.onnx and wlang_rnn_relu.onnx files gave the following error
```
[libprotobuf INFO google/protobuf/io/coded_stream.cc:610] Reading dangerously large protocol message.  If 
the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To
 increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/p
rotobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:81] The total number of bytes read was 54023761
terminate called after throwing an instance of 'migraphx::version_1::exception'
  what():  /home/mev/source/AMDMIGraphX/src/onnx/onnx.cpp:881: RNN: activation function Tanh not supported
```
so not sure if relu was actually exported.

Both the LSTM and GRU versions have undefined operators.

All four output files using read_onnx are attached below
[migraph_gru.txt](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/files/3287545/migraph_gru.txt)
[migraph_lstm.txt](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/files/3287546/migraph_lstm.txt)
[migraph_rnn_relu.txt](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/files/3287547/migraph_rnn_relu.txt)
[migraph_rnn_tanh.txt](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/files/3287548/migraph_rnn_tanh.txt)

**Comment by scxiao** [comment]
Undefined operators are expected for some input arguments of the RNN operators. 
For the activation function "Tanh" not exist, it is because onnx files contains names of both "Tanh" and "tanh", and current implementation only recognize "tanh". After we change to handle both lower case name and name with the first letter of capital, the error is gone. 

PR#273 is created for this problem.

**Comment by scxiao** [comment]
This issue is fixed, so close it.
