### ISSUE TITLE
MIGraphX incorrect results in develop branch

### ISSUE THREAD

**Issue by mvermeulen** [ROCmSoftwarePlatform/AMDMIGraphX#394]
Latest weekly build (23124b0) gives incorrect results for resnet50i1.onnx imagenet:
```
50000 top1: 43 top5: 253
Overall - top1: 0.00086 top5: 0.00506
```
It does have expected answers for imageneti1.onnx
```
50000 top1: 38823 top5: 46883
Overall - top1: 0.77646 top5: 0.93766
```
When run for TF resnet50v2 or for TF mobilenet it dumps core
```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

**Comment by mvermeulen** [comment]
Accuracy issues also appear with 756c5908c3de37e8560010872b875b1f818e2b83 checking results of 5f2767aad173b20d820421a8d2549172c4e6a66c now...

**Comment by pfultz2** [comment]
This comes from the fusion of the conv+conv. I am looking into why it fails verification. You can run resnet 50 with `--trim 161` to reproduce the issue with a smaller operations.

**Comment by mvermeulen** [comment]
It works with 5f2767aad173b20d820421a8d2549172c4e6a66c confirms was introduced with fusion of conv+conv
