### ISSUE TITLE
Provide C API to be called by onnxruntime

### ISSUE THREAD

**Issue by scxiao** [ROCmSoftwarePlatform/AMDMIGraphX#409]
To support migraphx as an execution provider, onnxruntime need to call migraphx APIs to run models on migraphx. We have an prototype implementation using the C++ API as the inteface, but it could have ABI issues with different binaries.

This task is to propose and implement a set of C APIs to be called by onnxruntime to avoid the above issues.

**Comment by mvermeulen** [comment]
Fixed
