### ISSUE TITLE
ONNX files tf_nasnet_large, tf_nasnet_mobile, tf_pnasnet_large fail with opset 10/11

### ISSUE THREAD

**Issue by mvermeulen** [ROCmSoftwarePlatform/AMDMIGraphX#438]
Running "driver read --onnx" for tf_nasnet_large, tf_nasnet_mobile and tf_pnasnet_large results in the following error for Opset 10 and Opset 11 versions
```
terminate called after throwing an instance of 'migraphx::version_1::exception'
  what():  /home/mev/source/AMDMIGraphX/src/include/migraphx/op/slice.hpp:72: in
consistent sizes
```
Running with Opset 7, Opset 8 and Opset 9 versions results in the following error
```
  what():  /home/mev/source/AMDMIGraphX/src/include/migraphx/op/concat.hpp:63: C
ONCAT: Non-axis dimensions should match
```
The set of operators used for these models are relatively small and do not change in Opset 10.  For example, here is the list of operators for tf_nasnet_large in both Opset 8 and Opset 10
```
	op    : Add
	op    : AveragePool
	op    : BatchNormalization
	op    : Concat
	op    : Conv
	op    : MatMul
	op    : MaxPool
	op    : Pad
	op    : ReduceMean
	op    : Relu
	op    : Slice
	op    : Softmax
	op    : Transpose
```

**Comment by kahmed10** [comment]
There is a problem with the slice operator, which is resulting in a shape of (0, 31, 55, 55) in nasnet mobile. The tensorflow pb works fine, so I will work on fixing the onnx version.

**Comment by scxiao** [comment]
With my changes of the slice operator, 
opset10:
tf_nasnet_large, tf_nasnet_mobile can be parsed and compiled correctly.
tf_pnasnet_large can be parsed correctly, but the simplify_algebra has an error like:
Pass: simplify_algebra
terminate called after throwing an instance of 'migraphx::version_1::exception'
  what():  /home/scxiao/Workplace/projects/AMDMIGraphX/src/include/migraphx/op/concat.hpp:63: CONCAT: Non-axis dimensions should match


Opset11: all three models has the following error:
  what():  /home/scxiao/Workplace/projects/AMDMIGraphX/src/include/migraphx/op/concat.hpp:63: CONCAT: Non-axis dimensions should match

Looks like there is a problem in our concat implementation.

**Comment by kahmed10** [comment]
> With my changes of the slice operator,
> opset10:
> tf_nasnet_large, tf_nasnet_mobile can be parsed and compiled correctly.
> tf_pnasnet_large can be parsed correctly, but the simplify_algebra has an error like:
> Pass: simplify_algebra
> terminate called after throwing an instance of 'migraphx::version_1::exception'
> what(): /home/scxiao/Workplace/projects/AMDMIGraphX/src/include/migraphx/op/concat.hpp:63: CONCAT: Non-axis dimensions should match
> 
> Opset11: all three models has the following error:
> what(): /home/scxiao/Workplace/projects/AMDMIGraphX/src/include/migraphx/op/concat.hpp:63: CONCAT: Non-axis dimensions should match
> 
> Looks like there is a problem in our concat implementation.

I don't think it's a concat issue. I ran with MIGRAPHX_TRACE_COMPILE=1, and tf_pnasnet_large/model.tf.pb was failing on the simplify algebra pass. When I disabled that pass, I was able to run the model.

**Comment by scxiao** [comment]
yes, I have the same observation for the tf_pnasnet_large opset10. After disabling the simplify_algebra, it can pass.

But opset11 models still have the problem.

**Comment by kahmed10** [comment]
I am not seeing any issues with the tf pb files in the opset11 models (with simplify_algebra disabled).

**Comment by scxiao** [comment]
With further investigation, the problem is in parsing the pad operator, which is in opset11, and our implementation is out of date. I have a branch with the fix and it can pass loading and compiling all three models in opset 11

**Comment by mvermeulen** [comment]
opset 10 passes.  Issue #457 added for opset 11 remaining problem.
