### ISSUE TITLE
ONNX files for Opset 9 candy, mosaic, pointilism, rain_princess and udnie get errors for padding support

### ISSUE THREAD

**Issue by mvermeulen** [ROCmSoftwarePlatform/AMDMIGraphX#441]
Running these ONNX files with the MIGraphX driver results in the following errors
```
  what():  /home/mev/source/AMDMIGraphX/src/onnx/onnx.cpp:1068: migraphx current
ly only supports constant padding
```

**Comment by kahmed10** [comment]
All of these models use "reflect" padding mode, which we currently do not support.

**Comment by kahmed10** [comment]
Currently there are no immediate plans to support "upsample," however reflect pad mode has been implemented.
