### ISSUE TITLE
ONNX files for Opset 8 fp16_tiny_yolov gets errors 

### ISSUE THREAD

**Issue by mvermeulen** [ROCmSoftwarePlatform/AMDMIGraphX#444]
Running this ONNX file with the MIGraphX driver results in the following errors
```
terminate called after throwing an instance of 'migraphx::version_1::exception'
  what():  /home/mev/source/AMDMIGraphX/src/include/migraphx/check_shapes.hpp:84
: Types do not match
```
Not 100% certain these are the same model, but fp32 Opset 8 version of tiny_yolov2 works without error.  I've attached a dump of ONNX files for both fp16 and fp32 models
[yolov_fp32.txt](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/files/4215865/yolov_fp32.txt)
[yolov_fp16.txt](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/files/4215866/yolov_fp16.txt)

**Comment by mvermeulen** [comment]
Note: Both the fp32 and fp16 versions are created from WinMLTools.  These are the only models in the test set that come from this provider.

**Comment by scxiao** [comment]
migraphx considers all attribute as float type, but input of the model is fp16, so there is a typemismatch.

**Comment by scxiao** [comment]
created a PR for the fix

**Comment by mvermeulen** [comment]
Implemented
