### ISSUE TITLE
fuse ops to remove unnecessary contiguous for BERT optimization

### ISSUE THREAD

**Issue by scxiao** [ROCmSoftwarePlatform/AMDMIGraphX#468]
With the Layernormalization and gemm-fusion performed, the output graph contains the following patterns, see @58 to @63,   and @64 to @70.

```
@53 = gpu::gemm[alpha=1,beta=1](@51,@52,@47,@47) -> float_type, {1, 128, 2304}, {294912, 2304, 1}: 0.0983568ms, 1%
@54 = load[offset=512,end=786944](@1) -> float_type, {1, 12, 128, 128}, {196608, 16384, 128, 1}: 0.0003492ms, 1%
@55 = multibroadcast[output_lens={1, 12, 128, 128}](@13) -> float_type, {1, 12, 128, 128}, {128, 0, 0, 1}: 0.0003674ms, 1%
@56 = gpu::contiguous(@55,@54) -> float_type, {1, 12, 128, 128}, {196608, 16384, 128, 1}: 0.0310097ms, 1%
@57 = load[offset=2359808,end=2753024](@1) -> float_type, {1, 128, 768}, {98304, 768, 1}: 0.00033062ms, 1%
===============================
@58 = slice[axes={2},starts={768},ends={1536}](@53) -> float_type, {1, 128, 768}, {294912, 2304, 1}: 0.00090682ms, 1%
@59 = gpu::contiguous(@58,@57) -> float_type, {1, 128, 768}, {98304, 768, 1}: 0.0293306ms, 1%
@60 = reshape[dims={1, 128, 12, 64}](@59) -> float_type, {1, 128, 12, 64}, {98304, 768, 64, 1}: 0.0005388ms, 1%
@61 = transpose[dims={0, 2, 3, 1}](@60) -> float_type, {1, 12, 64, 128}, {98304, 64, 1, 768}: 0.000431ms, 1%
@62 = load[offset=3146240,end=3539456](@1) -> float_type, {1, 12, 64, 128}, {98304, 8192, 128, 1}: 0.0003184ms, 1%
@63 = gpu::contiguous(@61,@62) -> float_type, {1, 12, 64, 128}, {98304, 8192, 128, 1}: 0.0364424ms, 1%
=================================
@64 = load[offset=2359808,end=2753024](@1) -> float_type, {1, 128, 768}, {98304, 768, 1}: 0.0003274ms, 1%
@65 = slice[axes={2},starts={0},ends={768}](@53) -> float_type, {1, 128, 768}, {294912, 2304, 1}: 0.0004848ms, 1%
@66 = gpu::contiguous(@65,@64) -> float_type, {1, 128, 768}, {98304, 768, 1}: 0.0271866ms, 1%
@67 = load[offset=3539456,end=3932672](@1) -> float_type, {1, 12, 128, 64}, {98304, 8192, 64, 1}: 0.000363ms, 1%
@68 = reshape[dims={1, 128, 12, 64}](@66) -> float_type, {1, 128, 12, 64}, {98304, 768, 64, 1}: 0.0003948ms, 1%
@69 = transpose[dims={0, 2, 1, 3}](@68) -> float_type, {1, 12, 128, 64}, {98304, 64, 768, 1}: 0.000386ms, 1%
@70 = gpu::contiguous(@69,@67) -> float_type, {1, 12, 128, 64}, {98304, 8192, 64, 1}: 0.0291015ms, 1%
===================================
@71 = load[offset=2359808,end=3146240](@1) -> float_type, {1, 12, 128, 128}, {196608, 16384, 128, 1}: 0.0003346ms, 1%

@72 = hip::copy(@56,@71) -> float_type, {1, 12, 128, 128}, {196608, 16384, 128, 1}: 0.0256694ms, 1%
@73 = gpu::gemm[alpha=0.125,beta=1](@70,@63,@72,@72) -> float_type, {1, 12, 128, 128}, {196608, 16384, 128, 1}: 0.0373719ms, 1%
```

The optimization is to fuse the slice, contiguous, reshape, transpose, and contiguous operations to get performance improvement.

**Comment by scxiao** [comment]
With the fusion, the performance improves from:

Summary:
gpu::gemm: 6.39793ms, 43%
hip::copy: 1.33224ms, 9%
gpu::add: 1.30492ms, 9%
gpu::layernorm: 1.28048ms, 9%
gpu::contiguous: 1.08452ms, 8%
gpu::slice_reshape_trans_contiguous: 0.793671ms, 6%
gpu::mul: 0.725441ms, 5%
gpu::gelu: 0.631943ms, 5%
gpu::softmax: 0.597145ms, 4%
hip::mul_add: 0.441767ms, 3%
load: 0.0949515ms, 1%
gpu::gather: 0.0925624ms, 1%
hip::hip_load_memory: 0.0802146ms, 1%
hip::triadd: 0.0291911ms, 1%
multibroadcast: 0.0271316ms, 1%
gpu::sub: 0.0256771ms, 1%
gpu::tanh: 0.0229813ms, 1%
gpu::convert: 0.0221306ms, 1%
reshape: 0.0120703ms, 1%
transpose: 0.0104036ms, 1%
slice: 0.0102755ms, 1%
@param: 0.00288362ms, 1%
unsqueeze: 0.00102702ms, 1%
check_context: 0.00077662ms, 1%

Rate: 103.815/sec
Total time: 9.63254ms
Total instructions time: 15.0223ms
Overhead time: 0.198517ms, -5.3898ms
Overhead: 2%, -56%

to:

Summary:
gpu::gemm: 6.98953ms, 44%
gpu::contiguous: 2.53288ms, 16%
hip::copy: 1.32333ms, 9%
gpu::layernorm: 1.29101ms, 8%
gpu::add: 1.28518ms, 8%
gpu::mul: 0.715304ms, 5%
gpu::gelu: 0.627955ms, 4%
gpu::softmax: 0.597194ms, 4%
hip::mul_add: 0.43835ms, 3%
load: 0.096646ms, 1%
gpu::gather: 0.0915433ms, 1%
hip::hip_load_memory: 0.0698336ms, 1%
hip::triadd: 0.0285154ms, 1%
multibroadcast: 0.0257348ms, 1%
gpu::sub: 0.0256578ms, 1%
gpu::tanh: 0.0232715ms, 1%
gpu::convert: 0.0220024ms, 1%
slice: 0.021717ms, 1%
reshape: 0.0198639ms, 1%
transpose: 0.0188298ms, 1%
@param: 0.00250402ms, 1%
unsqueeze: 0.0009486ms, 1%
check_context: 0.0005772ms, 1%

Rate: 94.1282/sec
Total time: 10.6238ms
Total instructions time: 16.2484ms
Overhead time: 0.217962ms, -5.62456ms
Overhead: 2%, -53%

10.3% improvement.

**Comment by mvermeulen** [comment]
Completed
