### ISSUE TITLE
"docker build -t migraphx ." fails for ROCm>=3.1

### ISSUE THREAD

**Issue by wbudd** [ROCmSoftwarePlatform/AMDMIGraphX#473]
GPU: **Radeon Pro WX 7100**
Docker host environment: **Ubuntu 18.04.1 LTS**

[Complete Docker build shell output text](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/files/4378606/amdmigraphx_log_output.txt)

**Comment by pfultz2** [comment]
So it most likely fails because its using rocm 3.1 which is installed into /opt/rocm-3.1 instead of /opt/rocm. You can add a line to symlink the directory in the Dockerfile: `ln -sd `realpath /opt/rocm-*` /opt/rocm`. In our CI, we are still using rocm 3.0. 

The Dockerfile is mainly for development, if you are wanting to use migraphx, the easiest way is to install it is with `apt install migraphx` after [installing rocm](https://github.com/RadeonOpenCompute/ROCm/blob/master/README.md#Ubuntu).

**Comment by wbudd** [comment]
Thank you for your quick solution—I've noticed now that this issue is [mentioned](https://github.com/RadeonOpenCompute/ROCm/blob/master/README.md#mivision-migraphx-installation) in the ROCm README.md. After including the line you suggested the docker build proceeds quite a bit further. Maybe best to update the Dockerfile by adding something like this?

     # If ROCm>=3.1, link its /opt/rocm-* installdir to the ROCm<3.1 default: /opt/rocm 
     [ -d /opt/rocm-* ] && ln -sd $(realpath /opt/rocm-*) /opt/rocm

However, the docker build is still not successful though. After a lengthy amount of compilation, it now fails to find opencl while configuring to build clang-ocl:

    [...]
    Successfully installed ROCmSoftwarePlatform/rocBLAS
    Downloading https://github.com/ROCmSoftwarePlatform/MIOpen/archive/2.0.0.tar.gz
    
    Extracting archive /usr/local/cget/build/tmp-5338396cbbcf48ed9d9273bf08aae52e/2.0.0.tar.gz ...
    Downloading https://github.com/RadeonOpenCompute/clang-ocl/archive/e605688ad932e6a946528a01943519bb6742c06a.tar.gz
    
    Extracting archive /usr/local/cget/build/tmp-43524cb19fe54399b44e110509ab9633/e605688ad932e6a946528a01943519bb6742c06a.tar.gz ...
    -- The C compiler identification is GNU 5.5.0
    -- The CXX compiler identification is Clang 9.0.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/local/bin/hcc
    -- Check for working CXX compiler: /usr/local/bin/hcc -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    CMake Error at CMakeLists.txt:23 (message):
    Can't find opencl


    -- Configuring incomplete, errors occurred!
    See also "/usr/local/cget/build/tmp-43524cb19fe54399b44e110509ab9633/build/CMakeFile/CMakeOutput.log".
    Command failed: ['/usr/bin/cmake', '-DCMAKE_TOOLCHAIN_FILE=/usr/local/cget/cget.cmake', '/usr/local/cget/build/tmp-43524cb19fe54399b44e110509ab9633/clang-ocl-e605688ad932e6a946528a01943519bb6742c06a', '-DCGET_CMAKE_DIR=/usr/local/lib/python3.5/dist-packages/cget/cmake', '-DCGET_CMAKE_ORIGINAL_SOURCE_FILE=/usr/local/cget/build/tmp-43524cb19fe54399b44e110509ab9633/clang-ocl-e605688ad932e6a946528a01943519bb6742c06a/__cget_original_cmake_file__.cmake', '-DMIOPEN_CACHE_DIR=', '-DBUILD_TESTING=Off', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_INSTALL_PREFIX=/usr/local/cget/pkg/RadeonOpenCompute__clang-ocl/install']
    Failed to build package ROCmSoftwarePlatform/MIOpen
    The command '/bin/sh -c cget -p $PREFIX install -f /dev-requirements.txt -DMIOPEN_CACHE_DIR=""' returned a non-zero code: 1

> The Dockerfile is mainly for development, if you are wanting to use migraphx, the easiest way is to install it is with apt install migraphx after installing rocm.

Right, understood. I'm actually trying both routes at the moment though, because I was hoping this Dockerfile would make it easier to integrate with some other containers/clusters I'm using. Plus, I figured this might give me easier access to any latest MIGraphX commits when necessary.

**Comment by wbudd** [comment]
In the meantime, I built the Docker image successfully by forcing usage of the ROCm 3.0 by replacing

    RUN curl https://raw.githubusercontent.com/RadeonOpenCompute/ROCm-docker/master/add-rocm.sh | bash

with

    RUN curl https://raw.githubusercontent.com/RadeonOpenCompute/ROCm-docker/master/add-rocm.sh | sed -e 's|/apt/debian/$|/apt/3.0/|' | bash

in the Dockerfile. (But I suppose this issue should stay open until Dockerfile handling of ROCm>=3.1 is implemented.)

**Comment by pfultz2** [comment]
> However, the docker build is still not successful though. After a lengthy amount of compilation, it now fails to find opencl while configuring to build MIOpen

Yea this another breaking change that happened in 3.1. A newer clang-ocl is needed for this. 

> Right, understood. I'm actually trying both routes at the moment though, because I was hoping this Dockerfile would make it easier to integrate with some other containers/clusters I'm using. Plus, I figured this might give me easier access to any latest MIGraphX commits when necessary.

Well it doesnt build migraphx in the dockerfile. If you want a dockerfile with a built migraphx in it, you could follow what is done for onnx runtime [here](https://github.com/ROCmSoftwarePlatform/onnxruntime/blob/migraphx/dockerfiles/Dockerfile.migraphx#L32). Here's a Dockerfile that could be used to build the latest migraphx:

```docker
FROM ubuntu:16.04

ENV DEBIAN_FRONTEND noninteractive
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

# Install rocm
RUN apt-get update && apt-get install -y --no-install-recommends curl && \
  curl -sL http://repo.radeon.com/rocm/apt/debian/rocm.gpg.key | apt-key add - && \
  sh -c 'echo deb [arch=amd64] http://repo.radeon.com/rocm/apt/debian/ xenial main > /etc/apt/sources.list.d/rocm.list'

# Install dependencis
RUN apt-get update &&\
    apt-get install -y sudo git bash build-essential cmake libpython3.5-dev python3-pip miopen-hip rocblas half

# If ROCm>=3.1, link its /opt/rocm-* installdir to the ROCm<3.1 default: /opt/rocm 
RUN [ -d /opt/rocm-* ] && ln -sd $(realpath /opt/rocm-*) /opt/rocm

# Install rbuild
RUN pip3 install https://github.com/RadeonOpenCompute/rbuild/archive/master.tar.gz

# Install MIGraphX from source
RUN mkdir -p /migraphx
RUN cd /migraphx && git clone --depth=1 --branch master https://github.com/ROCmSoftwarePlatform/AMDMIGraphX src
RUN cd /migraphx && rbuild package --cxx /opt/rocm/bin/hcc -d /migraphx/deps -B /migraphx/build -S /migraphx/src/ -DPYTHON_EXECUTABLE=/usr/bin/python3
RUN dpkg -i /migraphx/build/*.deb
RUN rm -rf /migraphx
```

**Comment by wbudd** [comment]
> Well it doesnt build migraphx in the dockerfile.
Haha, yes, I noticed that after it finished building... but I did manage to build MIGraphX from source within the resulting container at least.

> If you want a dockerfile with a built migraphx in it, you could follow what is done for onnx runtime here. Here's a Dockerfile that could be used to build the latest migraphx:
I didn't know about that one! Thanks, will try—that should simplifies things!

**Comment by mvermeulen** [comment]
We have newer docker file and versions as an example to address underlying issue.

**Comment by mvermeulen** [comment]
Closing, as it has been addressed.

If you still see an issue, please reopen.
