### ISSUE TITLE
mobilenet performance regression, more time spent in "clip"

### ISSUE THREAD

**Issue by mvermeulen** [ROCmSoftwarePlatform/AMDMIGraphX#475]
Weekly performance run shows a ~14% performance regression between 3/24 and 3/31.  Attached perf_report files seem to show more time spent in "clip" operation.

[mobilenet_0324.txt](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/files/4412131/mobilenet_0324.txt)
[mobilenet_0331.txt](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/files/4412132/mobilenet_0331.txt)

I haven't yet tried with/without PR 455, but filing issue so we capture it.

**Comment by kahmed10** [comment]
The plan is to add more passes to optimize relu6, which was previously using clip.

**Comment by causten** [comment]
Clip is back down to 7%.  ok to close?

**Comment by kahmed10** [comment]
performance looks improved now.
