### ISSUE TITLE
How should a debug build be created?

### ISSUE THREAD

**Issue by wbudd** [ROCmSoftwarePlatform/AMDMIGraphX#476]
I tried `ccmake ..` from the build directory, but I don't see any cmake flags that would enable such.

In particular, I would like to debug ONNX parsing to see exactly which network node(s) are causing errors.

(For now I simply added some `std::cout <<` prints to onnx.cpp, but given how excruciatingly long migraphx compile times are, this isn't a very comfortable approach).

**Comment by kahmed10** [comment]
Sorry the documentation wasn't clear, but look for the cmake flag CMAKE_BUILD_TYPE. By default, it should be set to "release," but you want to change it to "debug" and rebuild.

For debugging which onnx operators are not supported, I suggest the following: find all of the unique operators in your onnx file, then compare the list of operators found in onnx.cpp (starting from L47. You can use the python tools from onnx to extract the contents of the onnx file and list the operators for each node.

**Comment by pfultz2** [comment]
You can do a debug build by setting `CMAKE_BUILD_TYPE` to `Debug`. This flag should show under `ccmake .`.  I believe it already prints the program in debug mode. We should probably make this a runtime option.

If you just want to debug onnx parsing, you can set `MIGRAPHX_ENABLE_GPU` to `Off` to disable the gpu backend which should speed up building.

You can also speed up gpu builds by adding the `-fno-gpu-rdc` compiler flag to the build(ie added it to `CMAKE_CXX_FLAGS`). We should probably add that flag to our CMake scripts. 

Also, I use ccache to help improve build times(especially when switching between different modes). I pass `-DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache` to cmake the first time I configure.

Finally, when debugging its not easy to see some things in the debugger, but the `migraphx::program` class has a `debug_print` function that can print the program or instructions, which may help.
