### ISSUE TITLE
add_convs in simplify_algebra cause error for opset7/tf_pnasnet_large

### ISSUE THREAD

**Issue by scxiao** [ROCmSoftwarePlatform/AMDMIGraphX#477]
When compile the above model, it generates the following error message
src/include/migraphx/op/concat.hpp:63: CONCAT: Non-axis dimensions should match

By removing add_convs, the error message is gone.

Also applied to the same model in other opset versions.

**Comment by pfultz2** [comment]
Where can I get a copy of this onnx file?

**Comment by scxiao** [comment]
You can unzip the file 20191107.zip in the folder /home/pfultz/onnx in the test machine on which you have a lot of onnx files.
