### ISSUE TITLE
Exceptions are thrown in running some models in ONNXruntime.

### ISSUE THREAD

**Issue by scxiao** [ROCmSoftwarePlatform/AMDMIGraphX#483]
The two models that throw exceptions are:
opset9/LSTM_Seq_lens_unpacked 
opset10/mask_rcnn_keras

The command line to run these models are:
./onnx_test_runner -r 1 -c 1 ~/test/msft_models/opset9/LSTM_Seq_lens_unpacked/ -e migraphx

**Comment by scxiao** [comment]
Exception of opset9/LSTM_Seq_lens_unpacked is resolved, but it generate incorrect results. Again, CPU/GPU results are different when running on MIGraphX directly.

The model opset10/mask_rcnn_keras also throws exception in the CPU EP, and the error info is the same on CPU EP and MIGraphX EP, looks like it is a problem in onnxruntime.

**Comment by pfultz2** [comment]
> Exception of opset9/LSTM_Seq_lens_unpacked is resolved, but it generate incorrect results. Again, CPU/GPU results are different when running on MIGraphX directly.

What do you set the dim params to?

**Comment by scxiao** [comment]
The incorrect results between CPU and CPU is root caused and fixed. The reason is the checking of transposed matrix in GPU gemm is incomplete, which makes transposed input matrices like transpse{{1, 0, 2}} does not a contiguous after it. 

By adding one more checking, CPU and GPU results now are the same.

**Comment by pfultz2** [comment]
Can you open a PR for this fix?

**Comment by scxiao** [comment]
Just sync the repository and tried the model, it still report the same exception message as before. 

"Fatal error: Pad is not a registered function/op"

**Comment by pfultz2** [comment]
Where is this exception coming from? Do you have a backtrace?

**Comment by scxiao** [comment]
I believe this information is from the file graph.cc, line 1977 as:

      if (!node.op_) {
        return Status(ONNXRUNTIME, FAIL, "Fatal error: " + node.OpType() + " is not a registered function/op");
      }

I also observed the following code:
csharp/test/Microsoft.ML.OnnxRuntime.Tests/InferenceTest.cs:                skipModels["mask_rcnn_keras"] = "Pad is not a registered function/op";

I also tried loading the model using the onnx script, and some errors are reported:
  File "../onnx/infer_onnx.py", line 15, in <module>
    print(onnx.helper.printable_graph(original_model.graph))
  File "/home/scxiao/.local/lib/python3.6/site-packages/onnx/helper.py", line 552, in printable_graph
    in_strs.append(printable_value_info(inp))
  File "/home/scxiao/.local/lib/python3.6/site-packages/onnx/helper.py", line 493, in printable_value_info
    s = '{}[{}]'.format(s, printable_type(v.type))
  File "/home/scxiao/.local/lib/python3.6/site-packages/onnx/helper.py", line 481, in printable_type
    s += str(', ' + 'x'.join(map(printable_dim, t.tensor_type.shape.dim)))
  File "/home/scxiao/.local/lib/python3.6/site-packages/onnx/helper.py", line 472, in printable_dim
    assert which is not None

**Comment by scxiao** [comment]
Tested the latest onnxruntime, the exception is still there.

**Comment by scxiao** [comment]
Latest onnxruntime has the same issue on CPU EP, and this issue is unrelated to MIGraphX, so close it.
