### ISSUE TITLE
Models have different CPU/GPU results

### ISSUE THREAD

**Issue by scxiao** [ROCmSoftwarePlatform/AMDMIGraphX#484]
When running the models from MSFT, they generate incorrect result in onnx_test_runner.
These models are:
opset7
fp16_inception_v1
fp16_tiny_yolov2
tf_inception_v1 
tf_inception_v2 
tf_mobilenet_v1_1.0_224 
tf_mobilenet_v2_1.0_224 
tf_mobilenet_v2_1.4_224 

opset8
fp16_inception_v1
fp16_tiny_yolov2
tf_inception_v1 
tf_inception_v2 
tf_mobilenet_v1_1.0_224 
tf_mobilenet_v2_1.0_224 
tf_mobilenet_v2_1.4_224 

opset9
tf_inception_v1 
tf_inception_v2 
tf_mobilenet_v1_1.0_224 
tf_mobilenet_v2_1.0_224 
tf_mobilenet_v2_1.4_224 

opset10
tf_mobilenet_v2_1.0_224 
tf_mobilenet_v2_1.4_224 
tf_inception_v1 
tf_mobilenet_v1_1.0_224 
tf_inception_v2 

opset11
tf_mobilenet_v2_1.0_224 
tf_mobilenet_v2_1.4_224 
tf_inception_v1 
tf_mobilenet_v1_1.0_224 
tf_inception_v2 

I have a test program here, that can run a model on both CPU/GPU, and compare whether they are the same.  If you want, please contact me.

**Comment by scxiao** [comment]
With the fix from the ort-block PRs, I retested all the models, the following are what I got today:
Correct: increase from 104 to 129
Falls back to CPU: 11 (same as last time I reported)
Incorrect: from 30 to 5, and the five models are:
opset7: fp16_inception_v1, fp_tiny_yolov2
opset8: fp16_inception_v1, fp_tiny_yolov2
opset9: LSTM_Seq_lens_unpack

Exception:
opset10/mask_rcnn_keras (have the same exception running with CPU EP)

**Comment by mvermeulen** [comment]
Looks like some excellent results.  I will also update my spreadsheet with this information.

**Comment by scxiao** [comment]
@pfultz2 for the opset7/tf_inception_v1 model, the LRN is the first instruction that generates a nan output

**Comment by pfultz2** [comment]
I recall there was a bug we had with miopen's LRN, do you think thats related?

What the reduced program in migraphx? I can try and run a test with miopen.

**Comment by scxiao** [comment]
I ran that in the onnxruntime. I can try to grab the input to the LRN. I will let you know.

**Comment by scxiao** [comment]
@pfultz2 @kahmed10 I just shared you guys a file with the input and outputs I grabbed.

**Comment by pfultz2** [comment]
What the LRN configuration?

**Comment by mvermeulen** [comment]
Closing as we have more specific issues for models listed above (or have fixed them).
