### ISSUE TITLE
Many  operators are not supported for the model opset10/BERT_Squad

### ISSUE THREAD

**Issue by scxiao** [ROCmSoftwarePlatform/AMDMIGraphX#485]
BERT is an import model, but MIGRAPHX cannot support the following operator when running on onnxruntime. 

idx = 217, op_type = OneHot
idx = 200, op_type = Reshape
idx = 219, op_type = Reshape
idx = 229, op_type = Reciprocal
idx = 410, op_type = Reshape
idx = 406, op_type = Reshape
idx = 140, op_type = Reshape
idx = 131, op_type = ConstantOfShape
idx = 402, op_type = Reshape
idx = 419, op_type = Reshape
idx = 430, op_type = Reciprocal
idx = 456, op_type = Reciprocal
idx = 472, op_type = Reshape
idx = 468, op_type = Reshape
idx = 464, op_type = Reshape
idx = 481, op_type = Reshape
idx = 492, op_type = Reciprocal
idx = 518, op_type = Reciprocal
idx = 534, op_type = Reshape
idx = 530, op_type = Reshape
idx = 526, op_type = Reshape
idx = 543, op_type = Reshape
idx = 554, op_type = Reciprocal
idx = 580, op_type = Reciprocal
idx = 596, op_type = Reshape
idx = 592, op_type = Reshape
idx = 588, op_type = Reshape
idx = 605, op_type = Reshape
idx = 616, op_type = Reciprocal
idx = 642, op_type = Reciprocal
idx = 658, op_type = Reshape
idx = 654, op_type = Reshape
idx = 650, op_type = Reshape
idx = 667, op_type = Reshape
idx = 678, op_type = Reciprocal
idx = 704, op_type = Reciprocal
idx = 720, op_type = Reshape
idx = 716, op_type = Reshape
idx = 712, op_type = Reshape
idx = 729, op_type = Reshape
idx = 740, op_type = Reciprocal
idx = 766, op_type = Reciprocal
idx = 782, op_type = Reshape
idx = 778, op_type = Reshape
idx = 774, op_type = Reshape
idx = 791, op_type = Reshape
idx = 802, op_type = Reciprocal
idx = 828, op_type = Reciprocal
idx = 844, op_type = Reshape
idx = 840, op_type = Reshape
idx = 836, op_type = Reshape
idx = 853, op_type = Reshape
idx = 864, op_type = Reciprocal
idx = 890, op_type = Reciprocal
idx = 906, op_type = Reshape
idx = 902, op_type = Reshape
idx = 898, op_type = Reshape
idx = 915, op_type = Reshape
idx = 926, op_type = Reciprocal
idx = 952, op_type = Reciprocal
idx = 968, op_type = Reshape
idx = 964, op_type = Reshape
idx = 960, op_type = Reshape
idx = 977, op_type = Reshape
idx = 988, op_type = Reciprocal
idx = 1014, op_type = Reciprocal
idx = 1030, op_type = Reshape
idx = 1026, op_type = Reshape
idx = 1022, op_type = Reshape
idx = 1039, op_type = Reshape
idx = 1050, op_type = Reciprocal
idx = 1076, op_type = Reciprocal
idx = 1092, op_type = Reshape
idx = 1088, op_type = Reshape
idx = 1084, op_type = Reshape
idx = 1101, op_type = Reshape
idx = 1112, op_type = Reciprocal
idx = 1138, op_type = Reciprocal
idx = 1144, op_type = Reshape
idx = 1157, op_type = Reshape
idx = 1160, op_type = Reshape

**Comment by kahmed10** [comment]
Why are ConstantofShape and Reshape failing?

**Comment by scxiao** [comment]
For now, we use a static analysis of the input shape of these two operators and the constant folding capability in MIGraphX is not used.

**Comment by scxiao** [comment]
@kahmed10, are you going to add the OneHot operator? if not, I will do it.

**Comment by mvermeulen** [comment]
Fixed by adding operators as well as using constant folding from ORT.
