### ISSUE TITLE
Reshape constant folding in onnxruntime

### ISSUE THREAD

**Issue by scxiao** [ROCmSoftwarePlatform/AMDMIGraphX#493]
Since we do static analysis for the input shape for the reshape operator. Many cases where reshape can run on MIGraphX fall back to CPU. Some models are:

opset7/tf_resnet_v1_152
opset9/tf_inception_v3

**Comment by scxiao** [comment]
Mainly for the ConstantOfShape and Reshape for the BERT model in #485

**Comment by mvermeulen** [comment]
Completed using constant folding.
