### ISSUE TITLE
Padding with std::numeric_limits<half>::lowest() gives different results on CPU/GPU

### ISSUE THREAD

**Issue by kahmed10** [ROCmSoftwarePlatform/AMDMIGraphX#506]
Related to #484 for fp16_tiny_yolov2.  When Maxpool is called, there is asymmetric padding applied via the pad operator. The lowest value on the GPU for half is currently not correct (it is being set to 0). I created a simple unit test to verify this behavior.

```
FAILED: ../../test/onnx/maxpool_half_test.onnx
error: 0.203961
cpu:0.75, 0.75, 0.6875, 0.6875, -0.9375, 0.75, 0.75, 0.6875, 0.9375, 0.9375, 0.75, 0.9375, 0.9375, 0.9375, 0.9375, 0.625, 0.9375, 0.9375, 0.25, 0.25, -0.1875, 0.5, 0.5, 0.25, 0.25
gpu:0.75, 0.75, 0.6875, 0.6875, 0, 0.75, 0.75, 0.6875, 0.9375, 0.9375, 0.75, 0.9375, 0.9375, 0.9375, 0.9375, 0.625, 0.9375, 0.9375, 0.25, 0.25, 0, 0.5, 0.5, 0.25, 0.25
Cpu data is all zeros
Gpu data is all zeros
Max diff: 0.9375
Mismatch at 4: -0.9375 != 0
```

**Comment by scxiao** [comment]
In the file target/gpu/device/pad.cpp, we have the following code, 
        type device_val = value;
        if(float_equal(value, std::numeric_limits<float>::lowest()))
        {
            device_val = device_cast(std::numeric_limits<type>::lowest());
        }

Could this be the reason for the error?

**Comment by scxiao** [comment]
@kahmed10, can you point me where is the onnx file maxpool_half_test.onnx? I want to try it.

Thanks

**Comment by kahmed10** [comment]
I just modified the gen_onnx.py script as follows:
```
@onnx_test
def maxpool_half_test():
    x = helper.make_tensor_value_info('x', TensorProto.FLOAT16, [1, 1, 5, 5])
    y = helper.make_tensor_value_info('y', TensorProto.FLOAT16, [1, 1, 5, 5])

    node = onnx.helper.make_node('MaxPool',
                                 inputs=['x'],
                                 outputs=['y'],
                                 kernel_shape=[2, 2],
                                 auto_pad='SAME_UPPER')

    return ([node], [x], [y])
```

**Comment by kahmed10** [comment]
> In the file target/gpu/device/pad.cpp, we have the following code,
> type device_val = value;
> if(float_equal(value, std::numeric_limits::lowest()))
> {
> device_val = device_cast(std::numeric_limits::lowest());
> }
> 
> Could this be the reason for the error?

For some reason std::numeric_limits<type>::lowest() fails to set the correct value for fp16 on the GPU (it sets it to 0). The CPU is unaffected, and fp32 datatype works fine with this logic.
