### ISSUE TITLE
gelu optimzation caused opset10/BERT_squad to generate incorrect results on GPU

### ISSUE THREAD

**Issue by scxiao** [ROCmSoftwarePlatform/AMDMIGraphX#532]
The PR "Add gelu optimization" caused the MSFT bert model in opset10 to generated incorrect results.
@kahmed10 you can use the stand alone program I sent to you to reproduce the issue (CPU/GPU results are different)

**Comment by kahmed10** [comment]
Can you try using the environment variable `MIGRAPHX_DISABLE_FAST_GELU=1`?

**Comment by scxiao** [comment]
Looks like disabling fast gelu will generate correct results.

**Comment by scxiao** [comment]
After rerunning all the models, this issue is only related to the BERT model, and we can use the env var to control that.

**Comment by kahmed10** [comment]
I'm removing the ort-blocker label for now. If having the same CPU/GPU results matters in the future, we could potentially add gelu to the remap pass and implement a CPU version for gelu.

**Comment by kahmed10** [comment]
Created #536 to resolve future fast-math functions as well.
