### ISSUE TITLE
loop and if operators

### ISSUE THREAD

**Issue by mvermeulen** [ROCmSoftwarePlatform/AMDMIGraphX#533]
Some models including MLPerf SSD resnet include loop/if operators which do not run on MIGraphX

This issue to address this.

**Comment by scxiao** [comment]
In the attribute subgraph of these operators, operators like Greater, Less, Not, And, Or are usually used. We may need to add these operators accordingly as well as the bool datatype.

**Comment by mvermeulen** [comment]
Related to module development

**Comment by scxiao** [comment]
PR #678 is for the module class implementation with one module as a first step. Next step is multiple module support, then we can support the If and Loop operator.

**Comment by cagery** [comment]
Just a side info related to this issue: 
From evaluating ONNX model zoo, I only see _/models/vision/object_detection_segmentation/ssd-mobilenetv1/model/ssd_mobilenet_v1_10.onnx_ complaining about loop operator not known.

**Comment by mvermeulen** [comment]
Completed IF operator.  Can separate out LOOP.

**Comment by causten** [comment]
Please split to define what is in 1.3 and create a new issue for enhanced features in 1.4

**Comment by causten** [comment]
IF operator is already complete.
LOOP operator has a pull request #853 Once it mergers this issue can close

**Comment by causten** [comment]
853 has been merged.  This issue has been integrated!
