### ISSUE TITLE
zero size split

### ISSUE THREAD

**Issue by scxiao** [ROCmSoftwarePlatform/AMDMIGraphX#560]
One split unit test has a input of zero size (scalar input?), the onnx graph is 
graph fused_function_subgraph (
  %input[FLOAT, 0]
) {
  %output_1, %output_2, %output_3 = Split[axis = 0, split = [0, 0, 0]](%input)
  return %output_1, %output_2, %output_3
}

MIGraphX cannot run this model (might be due to 0 input shape)

**Comment by causten** [comment]
unlikely to ever work on this
