### ISSUE TITLE
Serialization

### ISSUE THREAD

**Issue by pfultz2** [ROCmSoftwarePlatform/AMDMIGraphX#572]
This issue is used to track the tasks needed to support serialization:

- [x] Initial serialization framework
- [x] Serialize value to and from json
- [x] Serialize value to and from mspack
- [x] Auto register all operators
- [x] Update GPU operators to make them serializable-friendly:
    - [x] Add reflect method to `hip_rnn_var_sl_shift_sequence`
    - [x] Add reflect method to `cpu_op`
    - [x] Store solver id for convolution
    - [x] Move gpu allocation for `hip_load_memory` to `finalize` method instead of in `preallocate_param`
    - [x] Move copying of literals for `hip_load_memory` to `finalize` method instead of in the `write_literals` pass
    - [x] Initialize fusion in finalize method instead of constructor for miopen fusion ops
    - [x] Dont reflect on miopenActivationMode_t for miopen_leaky_relu, miopen_elu, and miopen_abs
    - [x] Dont reflect on miopenLRNMode_t for miopen_lrn, 
- [x] Add to_value and from_value to operation
- [x] Add to_value and from_value to context
- [x] Add python/C APIs to construct operators
- [x] Add C++ APIs to construct operators
- [x] Serialize a program to disk
- [x] Deserialize a program from disk

**Comment by scxiao** [comment]
all items are finished and close it.
