### ISSUE TITLE
Empty input for the clip operator

### ISSUE THREAD

**Issue by scxiao** [ROCmSoftwarePlatform/AMDMIGraphX#580]
In onnx backend tests, the following tests failed because multibroadcast cannot support scalar input in which shape lens are zeros
test_clip_default_max_cpu
test_clip_default_inbounds_cpu

**Comment by scxiao** [comment]
The problem in this issue is related to the processing of empty input (undefined operator in migraphx) is not correct, created PR #625 to fix this issue.

**Comment by mvermeulen** [comment]
Fixed
