### ISSUE TITLE
ONNX export from pytorch 0.4.1 uses dynamic shapes

### ISSUE THREAD

**Issue by wsttiger** [ROCmSoftwarePlatform/AMDMIGraphX#59]
Currently, PyTorch 4.1 has multiple IR instructions to perform a simple flatten. We need to add a matcher (or some other logic) to detect this and replace with simple flatten.

**Comment by mvermeulen** [comment]
Note: pytorch 0.4.1 dynamic shape is potentially larger issue.  Edited the title of this issue to reflect the overall scope.

**Comment by mvermeulen** [comment]
Closed in favor of explicit issue for PyTorch 1.0 support.
