### ISSUE TITLE
Update Python interface to build Python 3.* versions simultaneously.

### ISSUE THREAD

**Issue by mvermeulen** [ROCmSoftwarePlatform/AMDMIGraphX#590]

**Comment by pfultz2** [comment]
[Here](https://github.com/pybind/pybind11/issues/748) is the related pybind11 issue. It looks like it was closed because of [this PR](https://github.com/pybind/pybind11/pull/2370), which adds a `PYBIND11_NOPYTHON` so that multiple python versions can be targeted.
