### ISSUE TITLE
Missing NonZero operator used in gpt-2 model

### ISSUE THREAD

**Issue by mvermeulen** [ROCmSoftwarePlatform/AMDMIGraphX#591]
Tried the gpt-2 model from the ONNX model zoo: https://github.com/onnx/models/blob/master/text/machine_comprehension/gpt-2/model/gpt2-10.onnx

This results in following error when running through MIGraphX:
```
terminate called after throwing an instance of 'migraphx::version_1::exception'
  what():  /src/AMDMIGraphX/src/onnx/onnx.cpp:2401: Unknown operator: NonZero
```
For completeness, following are the unique operators used in GPT2:
```
	op    : Add
	op    : Cast
	op    : Concat
	op    : Constant
	op    : ConstantOfShape
	op    : Div
	op    : Gather
	op    : Gemm
	op    : MatMul
	op    : Mul
	op    : NonZero
	op    : Pow
	op    : ReduceMean
	op    : Reshape
	op    : Shape
	op    : Slice
	op    : Softmax
	op    : Split
	op    : Sqrt
	op    : Squeeze
	op    : Sub
	op    : Tanh
	op    : Transpose
	op    : Unsqueeze
```

**Comment by kahmed10** [comment]
There is also the Huggingface GPT2 model that does not include `NonZero`, but instead is missing the `Where` operator.

**Comment by scxiao** [comment]
The NonZero output shape is essentially dynamic, and we will not be able to support it with the current MIGraphX implementation. But if we can constant folding the input of the NonZero, we will be fine. Also, there are other operators in this model reported unsupported. These operators are ConstantOfShape, Reshape, Slice, most likely some inputs are considered of dynamic shape. I need to check whether we can constant folding those input.

**Comment by scxiao** [comment]
Add parsing the NonZero operator, and MIGraphX can run this model now. Looks like input of the NonZero operator can be constant folded.
