### ISSUE TITLE
How to use the MIOpen fused kernels

### ISSUE THREAD

**Issue by learner321** [ROCmSoftwarePlatform/AMDMIGraphX#614]
Hi, I found that some fused kernels like conv+bias+activation has been implemented in MIOpen. How can I use this feature in AMDMIGraphx. I tested a simple case for classification, but there are no fused kernels in ~/.config/*.txt after running. Now the CBAinfer kernel may not support the `MIOPEN_FIND_ENFORCE=3` mode in MIOpen.

Other question is that if I want to add some new OPs for inferencing in AMDMIGraphx, how should I do, is there some docs?

**Comment by mvermeulen** [comment]
Closed, answer provided.
