### ISSUE TITLE
Error "Tensor dims 5 out of range"

### ISSUE THREAD

**Issue by scxiao** [ROCmSoftwarePlatform/AMDMIGraphX#617]
The attached model reported the above error message
[model.zip](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/files/5115548/model.zip)

It is likely related to the reduce-dim optimization

**Comment by scxiao** [comment]
Program is:
0 = @param:0 -> float_type, {1, 9, 4, 4}, {144, 16, 4, 1}
@0 = @literal{1, 1, 3, 3, 4, 4} -> int64_type, {6}, {1}
@1 = @literal{1, 1, 12, 12} -> int64_type, {4}, {1}
@2 = reshape[dims={1, 1, 3, 3, 4, 4}](0) -> float_type, {1, 1, 3, 3, 4, 4}, {144, 144, 48, 16, 4, 1}
@3 = transpose[dims={0, 1, 4, 2, 5, 3}](@2) -> float_type, {1, 1, 4, 3, 4, 3}, {144, 144, 4, 48, 1, 16}
@4 = contiguous(@3) -> float_type, {1, 1, 4, 3, 4, 3}, {144, 144, 36, 12, 3, 1}
@5 = reshape[dims={1, 1, 12, 12}](@4) -> float_type, {1, 1, 12, 12}, {144, 144, 12, 1}
@6 = @return(@5)

p1_inputname = 
0	
After compiling, program is: 
@0 = check_context -> float_type, {}, {}
@1 = hip::hip_allocate_memory[shape=float_type, {0}, {1},id=scratch] -> float_type, {0}, {1}
0 = @param:0 -> float_type, {1, 9, 4, 4}, {144, 16, 4, 1}
@2 = reshape[dims={1, 1, 3, 3, 4, 4}](0) -> float_type, {1, 1, 3, 3, 4, 4}, {144, 144, 48, 16, 4, 1}
@3 = transpose[dims={0, 1, 4, 2, 5, 3}](@2) -> float_type, {1, 1, 4, 3, 4, 3}, {144, 144, 4, 48, 1, 16}
#output_0 = @param:#output_0 -> float_type, {1, 1, 4, 3, 4, 3}, {144, 144, 36, 12, 3, 1}
@4 = gpu::contiguous(@3,#output_0) -> float_type, {1, 1, 4, 3, 4, 3}, {144, 144, 36, 12, 3, 1}
@5 = reshape[dims={1, 1, 12, 12}](@4) -> float_type, {1, 1, 12, 12}, {144, 144, 12, 1}
@6 = @return(@5)

**Comment by kahmed10** [comment]
PR #620 will fix this issue if merged in.

**Comment by mvermeulen** [comment]
Fixed
