### ISSUE TITLE
feature request - improve readme

### ISSUE THREAD

**Issue by flowpoint** [ROCmSoftwarePlatform/AMDMIGraphX#649]
hello,
this would improve accessibility and usability alot.
if you have time, you could take a minute and 
update the readme to add following information:

* who this library is for? is it a backend for api developers or intended to be used directly aswell?
* will / does it support just inference or inference and training?
* state of the library: unstable, stable, alpha, beta, ..., are breaking changes possible?
* add link to the hosted documentation to readme itself, not only in the github site

i wouldve send a PR if i could answer the questions myself.

PS. now or later you might want to add a contributing guideline, support contact information (im unsure if questions belong in github issues) and an issue template ( possibly shared with other rocm repos)
thank you

**Comment by mvermeulen** [comment]
Merged
