### ISSUE TITLE
Add frozen protobuf examples for TF 2.x

### ISSUE THREAD

**Issue by mvermeulen** [ROCmSoftwarePlatform/AMDMIGraphX#652]
It looks like the Slim repository is mostly back at TF 1.x, though there seem to be potential examples of follow on codes, e.g. https://www.tensorflow.org/guide/migrate

It also looks like the method of saving protobufs has changed from TF 1.x to TF 2.x.

This ticket is to create updated example of saving a TF model, exporting it to protobuf and then running it as input to MIGraphX

**Comment by mvermeulen** [comment]
Included with ROCm 0.9.

**Comment by causten** [comment]
work completed...  examples/export_frozen_graph_tf2
