### ISSUE TITLE
SSD detector in AMDMIGraphX

### ISSUE THREAD

**Issue by qianqing13579** [ROCmSoftwarePlatform/AMDMIGraphX#653]
I have developed ssd detector inference program.Here is the link: https://github.com/qianqing13579/MIGraphX_Samples. The program can run successfully in FP32 and FP16,but wrong in int8. When I use int8,there will be a big accuracy loss,and I do not know why.

**Comment by scxiao** [comment]
Did you use calibration data for the int8? i.e., when calling the int8_quantize(), is the argument m empty? In general, m should contain at least one real input as the calibration data. 

If m is empty, we will use a default value for the int8 quantization, this default value is most likely incorrect and affects the correctness of the inference.

**Comment by scxiao** [comment]
@qianqing13579 With the calibration data, I believe the correctness issue is gone, right?

**Comment by qianqing13579** [comment]
Yes,I have solved this issue. Thank you

**Comment by scxiao** [comment]
Fixed and close it
