### ISSUE TITLE
Correctness issues with ROCm 3.9 RC3

### ISSUE THREAD

**Issue by mvermeulen** [ROCmSoftwarePlatform/AMDMIGraphX#669]
Build a dockerfile for ROCm 3.9 RC3 candidate.  All the unit tests pass.  All the performance tests create results.  Imagenet results however, give me the following percentages:
```
inceptionv3-onnx.out:Overall - top1: 0.77286 top5: 0.9358
mobilenet-tf.out:Overall - top1: 0.001 top5: 0.00498
resnet50v2-onnx.out:Overall - top1: 0.75308 top5: 0.92522
resnet50v2-tf.out:Overall - top1: 0.00102 top5: 0.00512
```
So looks like something unique to TF frozen model examples is creating incorrect results.  Not sure of cause, but filing this issue to diagnose the problem.

Also posted a docker file as mevermeulen/rocm-migraphx:3.9-rc3 that contains built dockerfile.

Kicked off a build with latest MIGraphX sources using rocm-3.7 to make sure latest sources still work correctly.  When completed, will report here and also post docker file, most likely mevermeulen/rocm-migraphx:20201022

**Comment by mvermeulen** [comment]
Finished a correctness run using same MIGraphX sources
```
commit f279cda6ade4a1cca67d503ff4a3576c23ee7dc6
```
but using ROCm 3.7 instead.  In this case, do have expected correctness
```
inceptionv3-onnx.out:Overall - top1: 0.77286 top5: 0.9358
mobilenet-tf.out:Overall - top1: 0.71676 top5: 0.90118
resnet50v2-onnx.out:Overall - top1: 0.75308 top5: 0.92522
resnet50v2-tf.out:Overall - top1: 0.70762 top5: 0.90012
```
So there is something that when built and run in the ROCm 3.9 environment results in correctness issues for two TF models but not two ONNX models.  Unit tests pass and performance tests run to completion without errors.

docker image for passing instance is posted at mevermeulen/rocm-migraphx:20201022

**Comment by mvermeulen** [comment]
Added a docker container that includes the models in /root:
mevermeulen/rocm-migraphx:3.9-rc3-models
if @pfultz2 want to try verify.

**Comment by mvermeulen** [comment]
The problem also happens with ROCm 3.10, RC1.  Also in this case, all unit tests pass and the performance tests also run without complaint.  However, see the following behaviors.  For resnet50v2 accuracy is very low:
```
Overall - top1: 0.00102 top5: 0.00512
```
For mobilenet, the program crashes
```
Memory access fault by GPU node-1 (Agent handle: 0x3135410) on address (nil). Re
ason: Page not present or supervisor privilege.
```

When running verify on mobilenet, the attached "gdb.filt.txt" shows output of the following operation on a debuggable MIGraphX:
```
prompt% gdb ./driver
(gdb) run verify /root/mobilenet_i1.pb
(gdb) thread apply all backtrace
```
Looking at the threads, suggests that gpu::clip might be involved in this crash.
[gdb.filt.txt](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/files/5447098/gdb.filt.txt)

When running verify on resnet50v2, the attached "verify.txt" shows output of running
```
prompt% ./driver verify /root/resnet50v2_i1.pb
```

[verify.txt](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/files/5447132/verify.txt)

Also start push of following docker container with ROCm 3.10 rc1 and debuggable MIGraphX: mevermeulen/rocm-migraphx:3.10-rc1-gdb

It has the mobilenet TF file in it as well.  The resnet50v2 can be gotten from the ROCm 3.9 rc3 container

**Comment by pfultz2** [comment]
So the models fail verification in the driver. Mobilenet fails at the clip operator:

```
/opt/rocm/bin/migraphx-driver verify --trim 407 mobilenet_i1.pb
```

I havent reduced it yet for resnet50.

**Comment by pfultz2** [comment]
So resnet50 fails at the add operator quite late in the model:

```
/opt/rocm/bin/migraphx-driver verify resnet50v2_i1.pb --trim 100
```

**Comment by mvermeulen** [comment]
Further diagnosis information:
1. Initial failures appear to be compiler related and using build 6318 appears to have fixed these compiler issues.
2. Subsequent failures introduced in ROCm 3.10 appear to be problem with MIOpen kernel.  JIRA ticket - http://ontrack-internal.amd.com/browse/SWDEV-263191 has additional details for the narrowed case.

**Comment by causten** [comment]
Work completed
