### ISSUE TITLE
How to add a new operator?

### ISSUE THREAD

**Issue by qianqing13579** [ROCmSoftwarePlatform/AMDMIGraphX#677]
My model has an op that MIGraphX does not support. How to add the new op? Can you give a sample

**Comment by scxiao** [comment]
For different operators, the approach used is different. Could you please tell us which operator you want to add? After we know the the specific operator, we will know which approach is the most reasonable way to add it, then we may tell you a branch showing the specific changes of adding the operator.

**Comment by qianqing13579** [comment]
@scxiao ，can you give a sample of common used operators such as convolution,ReLU,pooling?

**Comment by scxiao** [comment]
You can check our PR#650 (closed PR)

**Comment by qianqing13579** [comment]
@scxiao ,  I have a SSD detector model,and there is a new op(Loop) in it. You can use netron to visualize it. I do not know how to add the new op.  Here is the link of the model: https://pan.baidu.com/s/1tYNLvvTzlquYYW0Qjz_haw, password: ln6o

**Comment by scxiao** [comment]
Implementation of Loop is different from other general operators since Loop contains subgraphs. We already had an issue #533 for the Loop and If operators. I am working on it now. We will be able to support it next release. I will let you know once it is ready.

**Comment by CharlieL7** [comment]
`Loop` operator is supported.
