### ISSUE TITLE
Fail to load GoogleNet

### ISSUE THREAD

**Issue by qianqing13579** [ROCmSoftwarePlatform/AMDMIGraphX#701]
I fail to load GoogleNet. The erroe message: src/include/migraphx/literal.hpp:82: void migraphx::version_1::literal::fill(Iterator, Iterator) [Iterator = float *]: Assertion `std::distance(start, end) == m_shape.elements()' failed.I do not know how to solve it. Here is the link of the model: https://pan.baidu.com/s/1EAYBO-MigTQOArMuHGNAXA
,password: r0dk

**Comment by scxiao** [comment]
@kahmed10 Just sent you the the downloaded model

**Comment by scxiao** [comment]
When I use an onnx python script to print initializers of this model, I get the following error
Traceback (most recent call last):
  File "print_onnx.py", line 65, in <module>
    print_initializers(original_model)
  File "print_onnx.py", line 47, in print_initializers
    array_v = numpy_helper.to_array(v)
  File "/home/scxiao/anaconda3/lib/python3.6/site-packages/onnx/numpy_helper.py", line 66, in to_array
    .reshape(dims)
ValueError: cannot reshape array of size 9408 into shape ()
So, maybe there are data corruption in the model.
@qianqing13579 Can you download the model and try again?

**Comment by qianqing13579** [comment]
@scxiao ，I will try.Thanks!

**Comment by kahmed10** [comment]
@qianqing13579 What is the difference between your model and the one in the official onnx model zoo?
https://github.com/onnx/models/blob/master/vision/classification/inception_and_googlenet/googlenet/model/googlenet-9.onnx

This one runs successfully through MIGraphX.

**Comment by qianqing13579** [comment]
@kahmed10 ，how to download this model

**Comment by kahmed10** [comment]
> @kahmed10 ，how to download this model

Click the "Download" button, or use this link:
https://github.com/onnx/models/raw/master/vision/classification/inception_and_googlenet/googlenet/model/googlenet-9.onnx

**Comment by kahmed10** [comment]
@qianqing13579 was this resolved?

**Comment by qianqing13579** [comment]
yes. Thanks
