### ISSUE TITLE
IF operator implementation

### ISSUE THREAD

**Issue by scxiao** [ROCmSoftwarePlatform/AMDMIGraphX#709]
Track the task of implementing the if operator in MIGraphX...

**Comment by scxiao** [comment]
It can be separated into subitems:
1) For the case of "cond" input to be constant, the subgraph can be inlined into the main module, and its implementation is straighted.
2) If the input "cond" is not a constant, sub_modules need to be created. In this case, we need the output shapes of the then and else branch to be the same and there is only one output for each subgraph. 
3) Extend operation to support multiple output, then we can supported the case of subgraph having multiple outputs. Tracked in issue #714.
4) then and else subgraph may have different shape (specified in the ONNX If operator, data_type is the same, but dims are different)

In this release, we will finish items 1) and 2). Most likely item 3) will be implementation, but have no plan to do item 4).

**Comment by scxiao** [comment]
Items implemented so far:
1. ref and gpu implementations of the IF operator
2. ref and gpu lowerings of the IF operator
3. Overload of the compute method with module inputs
4. Parse IF operator with non-const input
5. Extend the generic_eval to support submodules
6. Add computing implicit dependencies of instructions with submodules considered
7. Resolve scheduling across submodules (item 6 is used here)
8. Optimized argument copy between parent modules and submodules without an explicit copy
9. Sort the file names in the gpu/CMakeLists.txt in the alphabetical order
10. Working on a bug related to the return value of a subgraph is a constant (need no computation), caused by item 9).

**Comment by mvermeulen** [comment]
Complete.
