### ISSUE TITLE
Performance profiling and investigation on the BERT model

### ISSUE THREAD

**Issue by scxiao** [ROCmSoftwarePlatform/AMDMIGraphX#710]
This is to track the task of improve the BERT model performance on the MI100 GPU...

**Comment by mvermeulen** [comment]
JIRA ticket was filed.

Open a PR for known improvements, e.g. to take advantage of GEMMs improvements.

**Comment by mvermeulen** [comment]
JIRA: SWDEV-272604.  Updated severity for this defect.

**Comment by causten** [comment]
Improvements have been made
