### ISSUE TITLE
how to install migraphx

### ISSUE THREAD

**Issue by zhangjia3** [ROCmSoftwarePlatform/AMDMIGraphX#745]
hello！How to install migraphx ？

**Comment by kahmed10** [comment]
If you have ROCm already installed, you can use the same method to install MIGraphX. For example, on Ubuntu, it would be:
```
sudo apt-get install migraphx
```
You can refer to the following documentation to install ROCm: https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html
If you are trying to build from source, then you can follow the steps on the front page's README. If there are specific errors you experience, please feel free to elaborate as needed.

**Comment by zhangjia3** [comment]
I use apt-get install migraphx ,but importerror:

root@51daa310698a:/# python3
Python 3.6.9 (default, Jul 17 2020, 12:50:27)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import migraphx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /opt/rocm-3.7.0/lib/migraphx.so: undefined symbol: _Py_ZeroStruct
>>>

**Comment by scxiao** [comment]
From your information, looks like you are using the hip-clang docker container. The reason might be the python version in the binary does not match that in the container. 
You can build the source and install the binaries as:
```
git clone https://github.com/ROCmSoftwarePlatform/AMDMIGraphX.git
cd AMDMIGraphX
mkdir build
CXX=/opt/rocm-3.7.0/llvm/bin/clang++ cmake ..
make -j$(nproc)
make install
```
Then you can import the migraphx library

**Comment by zhangjia3** [comment]
Thank you very much for your help, I will try your suggestion like you.Now I am using migraphx to compile onnruntime-gpu, but onnxruntime cannot call gpu,like that：
root@51daa310698a:/# python3
Python 3.6.9 (default, Jul 17 2020, 12:50:27)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

import onnxruntime
'CPU-Migraphx'

**Comment by scxiao** [comment]
You can refer this example to how to use onnxruntime (see the help info with -h option), the execution provider name for AMDMIGraphX is "migraphx"

https://github.com/scxiao/ort_test/blob/master/python/run_onnx/test_run_onnx.py

**Comment by zhangjia3** [comment]
@scxiao I have followed the link you gave to test,it can run. But I am not sure whether the GPU is called. because I tested onnxruntime and just called'CPU-MIGRAPHX'.
Python 3.6.9 (default, Jul 17 2020, 12:50:27)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import onnxruntime
>>> onnxruntime.get_device()
'CPU-MIGRAPHX'
>>>

**Comment by zhangjia3** [comment]
![Uploading migraphx.JPG…]()

**Comment by zhangjia3** [comment]
![migraphx](https://user-images.githubusercontent.com/42707056/107180420-a2039a00-6a13-11eb-8fe0-1800b1268861.JPG)

**Comment by zhangjia3** [comment]
I have followed the link you gave to test,it can run. But I am not sure whether the GPU is called. because I tested onnxruntime and just called'CPU-MIGRAPHX'.
![migraphx](https://user-images.githubusercontent.com/42707056/107207948-e2770e00-6a3b-11eb-8604-dd0c4197bcf2.JPG)

**Comment by scxiao** [comment]
From the log information, the MIGraphX is available, you can set an environment variable MIGRAPHX_TRACE_EVAL=1 try the different options "--ep CPU" and "--ep migraphx" to see whether there is a difference.

**Comment by zhangjia3** [comment]
So far I have done some environmental tests,I have set the environment  in the inference  code like that thsession.set_providers(MIGraphXExecutionProvider)，The inference results are as follows，The inference speed is very slow, and the GPU should not be called
![f09768f77cb4094d8041197851618a5](https://user-images.githubusercontent.com/42707056/107244583-23394c00-6a69-11eb-90fa-cf4b6162c468.png)
And When I try to import the migraphx module, I get an import error as shown below，So I am not sure if the migraphx module I installed is correct. I also want to know if the migraphx module will only call the GPU and not the cpu. At the same time, thank you very much for your reply.
![111](https://user-images.githubusercontent.com/42707056/107245312-f9345980-6a69-11eb-8ad8-5c0bf8b02cff.PNG)

**Comment by scxiao** [comment]
Can you try the env var "MIGRAPHX_TRACE_EVAL=1"? 

How did you build the docker container? Did you use the dockerfile "Dockerfile.migraphx"?

**Comment by zhangjia3** [comment]
I don’t know how to set the environment variable MIGRAPHX_TRACE_EVAL=1 in the docker container during inference, can you tell me how to even?
I did not use dockerfile to build the docker container, because the domestic network is very poor and it cannot be successfully built. I pulled the docker image directly on dockerhub
https://hub.docker.com/r/mevermeulen/rocm-migraphx/tags?page=1&ordering=last_updated
docker pull mevermeulen/rocm-migraphx:20210118

**Comment by scxiao** [comment]
It can be run as "MIGRAPHX_TRACE_EVAL=1 your_cmd"

**Comment by zhangjia3** [comment]
I tried setting environment variables for inference test and the output is as follows，and  ,I set the environment in the inference code like that session.set_providers(MIGraphXExecutionProvider)
![mig2](https://user-images.githubusercontent.com/42707056/107338484-8f15c600-6af6-11eb-8fab-02cbf8ac8282.JPG)
And，when , set the environment in the inference code like that session.set_providers(CPUExecutionProvider)，the output is as follows
![mig3](https://user-images.githubusercontent.com/42707056/107339837-1a438b80-6af8-11eb-987b-0a165467f2c5.JPG)

**Comment by scxiao** [comment]
Your output indicates the function call session.set_providers(MIGraphXExecutionProvider) makes your model running on MIGraphX. The slowness is caused by the build of the model, which happens only for the first inference execution. The second inference will not build the model again and it is supposed to be much faster.

As for the above message "Instruction not part of the program", since you compiled the source code, you can try our driver in the "build/bin" folder with the command "MIGRAPHX_TRACE_EVAL=1 ./migraphx-driver verify your_model" to see whether we have the same info "Instruction not part of the program"?

**Comment by zhangjia3** [comment]
I know that the model will take time initially to cause the inference time of the first picture to be too slow, but the inference time of the subsequent pictures is 200ms, but my inference time under PyTorch only needs about 20ms, using the same AMD graphics card. And when I modify session.set_providers(MIGraphXExecutionProvider) to session.set_providers(CPUXExecutionProvider), the inference time of the two is almost the same. So I suspect that the GPU is not called during inference. In addition, due to network reasons, I cannot use dockerfile to build a migraphx_onnxruntime mirror. If you have a mirror that has already been built, can you provide a copy? I will conduct a new test. Finally, thank you for your reply.

**Comment by scxiao** [comment]
Maybe you can try the following onnxruntime docker image to see what is the output.
docker pull scxiao/onnxruntime_migraphx:rocm3.7

**Comment by zhangjia3** [comment]
Thank you very much for the mirror image, but I got the following error while testing. Does this image have requirements for the device, my device is gfx803
![mmexport1612959050227](https://user-images.githubusercontent.com/42707056/107508879-9911f480-6bdc-11eb-8b80-11540307e913.png)

**Comment by scxiao** [comment]
Are you using the following command line to create the container?
```docker run -it --device=/dev/kfd --device=/dev/dri --group-add video --cap-add SYS_PTRACE scxiao/onnxruntime_migraphx:rocm3.7```

**Comment by zhangjia3** [comment]
yes ,I  have done it ,The currently located error is reported when reading the onnx model, my model is converted from AMD_pytorch。My model conversion code is as follows:
![mmexport1613008019384](https://user-images.githubusercontent.com/42707056/107594984-5f79d180-6c4e-11eb-8e40-d9a1ec0770f7.png)
An error is reported when reading the onnx model during inference, the code is as follows
![mmexport1613008016762](https://user-images.githubusercontent.com/42707056/107595040-8801cb80-6c4e-11eb-98c3-6324e88b703c.png)

**Comment by zhangjia3** [comment]
@scxiao Using gfx906 device can solve the problem of device non-adaptation. But the inference speed is still very slow.

**Comment by kahmed10** [comment]
What kind of model are you trying to run? If it is convolution-based, then it could be because that MIOpen isn't tuned. You can refer to this wiki page here: https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/wiki/resnext-,-a-case-study-demonstrating-the-importance-of-library-tuning

Essentially, you can try running your model once with the MIOpen flag enabled:
`MIOPEN_FIND_ENFORCE=3 [your_cmd]`

This tuning step may take awhile, but ideally it should improve performance, especially on a model like Resnet.

**Comment by zhangjia3** [comment]
@scxiao Thank you very much for your help. After I have performed performance tuning, the speed has been greatly improved, but I cannot install OpenCV-Python in the provided image creation. Can you tell me how to do it?

**Comment by zhangjia3** [comment]
@kahmed10 @scxiao  I can not pip install opencv-python in the image of scxiao/onnxruntime_migraphx:rocm3.7 。The numpy version is incorrect, but no other version can be installed. Can you try to install it in the container? Could you please tell me how to install it if possible? Thank you very much for your help

**Comment by scxiao** [comment]
You can first uninstall the numpy as 

```
pip3 uninstall numpy
```

Then install the specified numpy vesion as:

```
pip3 install numpy==x.xx.xx
```

Then install opencv-python as:

```
pip3 install opencv-python
```

**Comment by zhangjia3** [comment]
@scxiao I have tried this method, onnxruntime1.6 requires numpy to be at least 1.16, opencv-python requires numpy to be 1.13, version conflict. I will try the method of Sudo apt-apt install python3-opencv But  if you could update the image of install OpenCV-Python，I'll be very grateful to you

**Comment by scxiao** [comment]
OK, you can try the apt install first, if it does not work, can you put the commands you run and the error message here, then we can try whether we can reproduce the problem and then we can know whether the new image can resolve the problem.

**Comment by zhangjia3** [comment]
@scxiao I have tried the apt install ,but I can not import cv2 .
![1111111](https://user-images.githubusercontent.com/42707056/110923110-7d287c80-835b-11eb-8462-06e6527f2ad4.JPG)

**Comment by scxiao** [comment]
After some investigation, the problem is that the python-opencv is for python3.6, but python3.7 is used by default in the container.
If you use the ```apt update && apt install python3-opencv``` to install the opencv, then you can import the opencv in python3.6 as:

```
python3.6
import cv2
```

The following is what I get:

```
>>> 
root@289fe75d69d4:/code# python3.6
Python 3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> 
````

**Comment by zhangjia3** [comment]
Thank you for your reply，Python3.6 can import onnxruntime？




---Original---
From: "Shucai ***@***.***&gt;
Date: Sat, Mar 13, 2021 07:30 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ROCmSoftwarePlatform/AMDMIGraphX] how to install migraphx (#745)




 
After some investigation, the problem is that the python-opencv is for python3.6, but python3.7 is used by default in the container.
 If you use the apt update &amp;&amp; apt install python3-opencv to install the opencv, then you can import the opencv in python3.6 as:
 python3.6 import cv2  
The following is what I get:
 &gt;&gt;&gt;  ***@***.***:/code# python3.6 Python 3.6.9 (default, Oct  8 2020, 12:12:24)  [GCC 8.4.0] on linux Type "help", "copyright", "credits" or "license" for more information. &gt;&gt;&gt; import cv2 &gt;&gt;&gt;

**Comment by scxiao** [comment]
Yes, I can import onnxruntime in my container

**Comment by zhangjia3** [comment]
OK，I will try it。



---Original---
From: "Shucai ***@***.***&gt;
Date: Sat, Mar 13, 2021 07:50 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ROCmSoftwarePlatform/AMDMIGraphX] how to install migraphx (#745)




 
Yes, I can import onnxruntime in my container

**Comment by douglastehling** [comment]
Hi, I'm in need of help.
I have a .onnx model and I need to run it on my machine. the GPU is an AMD Radeon Vega 8. Looking for how to run, I found AMDMIGraphX, but it only has instructions for running on linux, and I need to run on windows. Do you know if it is possible?

**Comment by kahmed10** [comment]
> Hi, I'm in need of help.
> I have a .onnx model and I need to run it on my machine. the GPU is an AMD Radeon Vega 8. Looking for how to run, I found AMDMIGraphX, but it only has instructions for running on linux, and I need to run on windows. Do you know if it is possible?

Unfortunately Vega 8 is not supported in MIGraphX regardless of Windows vs Linux. You may still be able to run the model through [tensorflow-directml](https://github.com/microsoft/tensorflow-directml). However, first you need to convert the .onnx model into a tf SavedModel. You can do this through [onnx-tensorflow](https://github.com/onnx/onnx-tensorflow). Once it is converted, you can simply use the python API in tensorflow and load the SavedModel accordingly.

**Comment by douglastehling** [comment]
> > Hi, I'm in need of help.
> > I have a .onnx model and I need to run it on my machine. the GPU is an AMD Radeon Vega 8. Looking for how to run, I found AMDMIGraphX, but it only has instructions for running on linux, and I need to run on windows. Do you know if it is possible?
> 
> Unfortunately Vega 8 is not supported in MIGraphX regardless of Windows vs Linux. You may still be able to run the model through [tensorflow-directml](https://github.com/microsoft/tensorflow-directml). However, first you need to convert the .onnx model into a tf SavedModel. You can do this through [onnx-tensorflow](https://github.com/onnx/onnx-tensorflow). Once it is converted, you can simply use the python API in tensorflow and load the SavedModel accordingly.

thank you very much for your help .. i will try to go in that direction

**Comment by zhangjia3** [comment]
@scxiao Hello，sorry to disturb you again. How to use the c++API interface of onnxruntime to inference?Do I need to recompile the migraphx library and onnxruntime library? How to compile if needed

**Comment by causten** [comment]
original question has been answered.  Open a separate issue for next question
