### ISSUE TITLE
MLIR MIOpen Dialect integration (phase 1)

### ISSUE THREAD

**Issue by sjw36** [ROCmSoftwarePlatform/AMDMIGraphX#768]
Integrate MLIR to enable MIOpen Dialect for iGEMM usage.

- Import MLIR libraries and C-API headers
- Add a pass to the GPU target before lowering that:
  - Find convolutions supported by MLIR dialect
  - Call MLIR C-API to generate kernel binaries
  - Substitute the gpu::convolution with a code_object_op

**Comment by mvermeulen** [comment]
Closing as merged.
