### ISSUE TITLE
issues after upgrading to ONNX 1.8.1

### ISSUE THREAD

**Issue by scxiao** [ROCmSoftwarePlatform/AMDMIGraphX#771]
After upgrading to ONNX 1.8.1, a few onnx unit tests failed, specifically:

1. Unsqueeze/Squeeze
   axes is changed from an attribute to the second input

2. ReduceSum
   axes is changed from an attribute to the second input
   note: Other reduce operators do not have this change.

3. Softmax/logsoft
   algorithm in these two operators are chagned. It is changed to match MIGraphX implementation, so we can turn on related
   unit tests. Here, we need to check the onnx version to ensure these tests are only turned on in onnx 1.8.0 or later...

4. quantizelinear
   Unit tests failed.

**Comment by mvermeulen** [comment]
Fixed.
