### ISSUE TITLE
MIGraphX Inference Examples and Deployment

### ISSUE THREAD

**Issue by cagery** [ROCmSoftwarePlatform/AMDMIGraphX#773]
General goals are highlighted below. 

- [ ] Model optimizer
- [ ] Inference examples
- [ ] Out-of-box experience improvements

**Comment by cagery** [comment]
Added #776 for BERT-based question answering example

**Comment by cagery** [comment]
PR'ed #776 #789 for release #766

**Comment by mvermeulen** [comment]
Closing this for 1.2; and will reopen separate tickets for 1.3.
