### ISSUE TITLE
Regression: taau model crashes with latest MIGraphX

### ISSUE THREAD

**Issue by mvermeulen** [ROCmSoftwarePlatform/AMDMIGraphX#790]
The following command crashes with AMDMIGraphX:
```
./driver perf /home/mev/source/rocm-migraphx/saved-models/onnx-misc/taau_low_res_downsample_d2s_for_infer_time_fp16_opset11.onnx --input-dim @inputs 1 1920 1080 8
```
In particular, following is the output:
```
Reading: /home/mev/source/rocm-migraphx/saved-models/onnx-misc/taau_low_res_downsample_d2s_for_infer_time_fp16_opset11.onnx
module: "main"
main:@0 = @literal{1, 16, 480, 270} -> int64_type, {4}, {1}
inputs = @param:inputs -> half_type, {1, 1920, 1080, 8}, {16588800, 8640, 8, 1}
main:@1 = @literal{0.517578, 0.548828, 0.405029, 0.48291} -> half_type, {4}, {1}
main:@2 = @literal{ ... } -> half_type, {4, 16, 3, 3}, {144, 9, 3, 1}
main:@3 = @literal{ ... } -> half_type, {16}, {1}
main:@4 = @literal{ ... } -> half_type, {16, 16, 3, 3}, {144, 9, 3, 1}
main:@5 = @literal{ ... } -> half_type, {16}, {1}
main:@6 = @literal{ ... } -> half_type, {16, 16, 1, 1}, {16, 1, 1, 1}
main:@7 = @literal{0} -> half_type, {0}, {1}
main:@8 = @literal{0} -> half_type, {0}, {1}
main:@9 = @literal{1} -> int32_type, {1}, {1}
main:@10 = @literal{-1} -> int32_type, {1}, {1}
main:@11 = @literal{-3} -> int32_type, {1}, {1}
main:@12 = @literal{ ... } -> half_type, {16}, {1}
main:@13 = @literal{ ... } -> half_type, {16, 16, 3, 3}, {144, 9, 3, 1}
main:@14 = @literal{ ... } -> half_type, {16}, {1}
main:@15 = @literal{ ... } -> half_type, {16, 16, 1, 1}, {16, 1, 1, 1}
main:@16 = @literal{0} -> half_type, {0}, {1}
main:@17 = @literal{0} -> half_type, {0}, {1}
main:@18 = @literal{1} -> int32_type, {1}, {1}
main:@19 = @literal{-1} -> int32_type, {1}, {1}
main:@20 = @literal{-3} -> int32_type, {1}, {1}
main:@21 = @literal{ ... } -> half_type, {16}, {1}
main:@22 = @literal{ ... } -> half_type, {16, 16, 3, 3}, {144, 9, 3, 1}
main:@23 = @literal{ ... } -> half_type, {16}, {1}
main:@24 = @literal{ ... } -> half_type, {16, 16, 1, 1}, {16, 1, 1, 1}
main:@25 = @literal{0} -> half_type, {0}, {1}
main:@26 = @literal{0} -> half_type, {0}, {1}
main:@27 = @literal{1} -> int32_type, {1}, {1}
main:@28 = @literal{-1} -> int32_type, {1}, {1}
main:@29 = @literal{-3} -> int32_type, {1}, {1}
main:@30 = @literal{ ... } -> half_type, {16}, {1}
main:@31 = @literal{ ... } -> half_type, {16, 16, 3, 3}, {144, 9, 3, 1}
main:@32 = @literal{ ... } -> half_type, {16}, {1}
main:@33 = @literal{ ... } -> half_type, {16, 16, 3, 3}, {144, 9, 3, 1}
main:@34 = @literal{ ... } -> half_type, {16}, {1}
main:@35 = @literal{ ... } -> half_type, {16, 16, 3, 3}, {144, 9, 3, 1}
main:@36 = @literal{ ... } -> half_type, {16}, {1}
main:@37 = @literal{ ... } -> half_type, {16, 8, 3, 3}, {72, 9, 3, 1}
main:@38 = transpose[dims={0, 3, 1, 2}](inputs) -> half_type, {1, 8, 1920, 1080}, {16588800, 1, 8640, 8}
main:@39 = convolution[padding={1, 1},stride={1, 1},dilation={1, 1},group=1,padding_mode=1](main:@38,main:@37) -> half_type, {1, 16, 1920, 1080}, {33177600, 1, 17280, 16}
main:@40 = broadcast[axis=1,dims={1, 16, 1920, 1080}](main:@36) -> half_type, {1, 16, 1920, 1080}, {0, 1, 0, 0}
main:@41 = add(main:@39,main:@40) -> half_type, {1, 16, 1920, 1080}, {33177600, 1, 17280, 16}
main:@42 = leaky_relu[alpha=0.3](main:@41) -> half_type, {1, 16, 1920, 1080}, {33177600, 1, 17280, 16}
main:@43 = pooling[mode=max,padding={0, 0},stride={2, 2},lengths={2, 2},ceil_mode=1](main:@42) -> half_type, {1, 16, 960, 540}, {8294400, 1, 8640, 16}
main:@44 = convolution[padding={1, 1},stride={1, 1},dilation={1, 1},group=1,padding_mode=1](main:@43,main:@35) -> half_type, {1, 16, 960, 540}, {8294400, 1, 8640, 16}
main:@45 = broadcast[axis=1,dims={1, 16, 960, 540}](main:@34) -> half_type, {1, 16, 960, 540}, {0, 1, 0, 0}
main:@46 = add(main:@44,main:@45) -> half_type, {1, 16, 960, 540}, {8294400, 1, 8640, 16}
main:@47 = leaky_relu[alpha=0.3](main:@46) -> half_type, {1, 16, 960, 540}, {8294400, 1, 8640, 16}
main:@48 = pooling[mode=max,padding={0, 0},stride={2, 2},lengths={2, 2},ceil_mode=1](main:@47) -> half_type, {1, 16, 480, 270}, {2073600, 1, 4320, 16}
main:@49 = convolution[padding={1, 1},stride={1, 1},dilation={1, 1},group=1,padding_mode=1](main:@48,main:@33) -> half_type, {1, 16, 480, 270}, {2073600, 1, 4320, 16}
main:@50 = broadcast[axis=1,dims={1, 16, 480, 270}](main:@32) -> half_type, {1, 16, 480, 270}, {0, 1, 0, 0}
main:@51 = add(main:@49,main:@50) -> half_type, {1, 16, 480, 270}, {2073600, 1, 4320, 16}
main:@52 = leaky_relu[alpha=0.3](main:@51) -> half_type, {1, 16, 480, 270}, {2073600, 1, 4320, 16}
main:@53 = pooling[mode=max,padding={0, 0},stride={2, 2},lengths={2, 2},ceil_mode=1](main:@52) -> half_type, {1, 16, 240, 135}, {518400, 1, 2160, 16}
main:@54 = convolution[padding={1, 1},stride={1, 1},dilation={1, 1},group=1,padding_mode=1](main:@53,main:@31) -> half_type, {1, 16, 240, 135}, {518400, 1, 2160, 16}
main:@55 = broadcast[axis=1,dims={1, 16, 240, 135}](main:@30) -> half_type, {1, 16, 240, 135}, {0, 1, 0, 0}
main:@56 = add(main:@54,main:@55) -> half_type, {1, 16, 240, 135}, {518400, 1, 2160, 16}
main:@57 = leaky_relu[alpha=0.3](main:@56) -> half_type, {1, 16, 240, 135}, {518400, 1, 2160, 16}


terminate called after throwing an instance of 'migraphx::version_1::exception'
  what():  /src/AMDMIGraphX/src/include/migraphx/check_shapes.hpp:136: standard: reshape: Shapes are not in standard layout
Aborted (core dumped)
```
This fails with commit abe4ec3e17a6a36db3aadfd347b9bafa34b8300b (docker image: mevermeulen/rocm-migraphx:4.1-20210405)

It passed last week with commit 5d601ad1497b2590c4c24463eb98d5a20a92d17 (docker image: mevermeulen/rocm-migraphx:4.1-20210329)

There are two PRs that were added between these commits: PR #777 from @pfultz2 and PR #765 from @scxiao 

Doing a "driver read" by itself or a "driver perf" without the "--input-dim" option works without core dumping.  However, adding the "--input-dim" option to the perf command causes things to crash.

**Comment by scxiao** [comment]
Just checked and it looks like #765 works fine.
By checking the graph above, it looks like the output shape of leaky_relu is a non-standard shape, but the next reshape needs a standard input shape. Maybe we need a check for input shape of reshape. If not a standard shape, we can add a contiguous before shape, which might be removed later by optimization.

**Comment by scxiao** [comment]
@pfultz2 If you are fine, I can fix it in my PR #784 (optimize resize and where)?

**Comment by pfultz2** [comment]
> Maybe we need a check for input shape of reshape. If not a standard shape, we can add a contiguous before shape, which might be removed later by optimization.

We already do this in the onnx parser [here](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/blob/develop/src/onnx/parse_reshape.cpp#L34). The `make_contiguous` function will add a contiguous operator if the input is not standard shape. I think more investigation is needed. Most likely we are doing a transformation of the graph that is changing the layout.

> If you are fine, I can fix it in my PR #784 (optimize resize and where)?

I think it would be better in a seperate PR.

**Comment by scxiao** [comment]
After adding a contiguous before the reshape in parsing the resize operator, the issue is gone, and the performance is the same.

**Comment by scxiao** [comment]
> > Maybe we need a check for input shape of reshape. If not a standard shape, we can add a contiguous before shape, which might be removed later by optimization.
> 
> We already do this in the onnx parser [here](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/blob/develop/src/onnx/parse_reshape.cpp#L34). The `make_contiguous` function will add a contiguous operator if the input is not standard shape. I think more investigation is needed. Most likely we are doing a transformation of the graph that is changing the layout.

The reason is output shape of the leak_relu is always standard before. With your PR propagating non-standarad shapes in more operators, the output shape of the leakrelu is non-standard in this model. Then when we parse the resize, the first operator used is reshape, which needs a standard shape.

**Comment by scxiao** [comment]
A more complete change is checking the input shape for all operators requiring standard shape. For a non-standard shape, we need to add contiguous, which will be either removed later or definitely required to run the model.
If we do not fix in this way, we will meet the problem again in other models.

**Comment by pfultz2** [comment]
> The reshape added here is in the function parse_resize(), in which no contiguous is added.

I see, so parse_resize needs to call `make_contiguous` as well.

> A more complete change is checking the input shape for all operators requiring standard shape.

I am not sure how we can do that everywhere we add reshape.

Either way, to fully support NHWC we need reshape to support transposed inputs. I am not sure exactly how yet.

**Comment by scxiao** [comment]
> > The reshape added here is in the function parse_resize(), in which no contiguous is added.
> 
> I see, so parse_resize needs to call `make_contiguous` as well.
> 
> > A more complete change is checking the input shape for all operators requiring standard shape.
> 
> I am not sure how we can do that everywhere we add reshape.
> 
> Either way, to fully support NHWC we need reshape to support transposed inputs. I am not sure exactly how yet.

Since the unet model is used in our weekly performance test, I prefer creating a PR to fix this specific issue first. Is that OK?

**Comment by pfultz2** [comment]
> I prefer creating a PR to fix this specific issue first. Is that OK?

Yea, just fix the resize, we can look at supporting reshape for more things in the future.

**Comment by mvermeulen** [comment]
Fixed.
