### ISSUE TITLE
enhance reshape to support non-standard input

### ISSUE THREAD

**Issue by scxiao** [ROCmSoftwarePlatform/AMDMIGraphX#793]
With more operators will generate outputs with non-standard outputs, it is necessary for the reshape operator to be able to handle non-standard input. 

This issue is to track enhancing the reshape operator...

**Comment by pfultz2** [comment]
We can only do reshape when the dimensions to be collapsed are adjacent. So we will need to do some analysis to find out which dimensions are being collapsed and then throw an error if they are not adjacent. For squeeze and unsqueeze we already now what dimensions will be collapsed so it will be simpler.
