### ISSUE TITLE
Support for ONNX runtime quantization

### ISSUE THREAD

**Issue by scxiao** [ROCmSoftwarePlatform/AMDMIGraphX#805]
Quantization is a useful approach to run models more efficiently. It runs a model using data types of lower procession (e.g., for a model with fp32, it first converts the data type to fp16 or int8, then runs the model in fp16 or int8), so some math operators can run faster.  MIGraphX has some preliminary support for quantization, but performance improvement achieved is not as good as what we expect, particularly for the int8 quantization. One reason is the rocblas APIs needs input data to be packed format (int8x4), which needs expensive preprocessing of input data in some scenarios. Recently, the rocblas removed the requirement for our latest generations of hardware, so the expensive preprocessing becomes unnecessary. On the other hand, ONNX Runtime (ORT) proposed the Q/DQ operators to support quantization of model in a general way, which, in turn, needs various execution providers to support that. Because of these changes, MIGraphX needs a few updates to better support int8 quantization, and we hope such updates can achieve much better performance than what we have now.  

For now, we identified the following tasks in the migraphx to support int8 quantization:
1) Changes gemm call for int8 data type 
    This change is to support input of all size. Current rocblas for int8 needs the "k" to be multiple of 4 for input matrices of size (m x k) and (k x n). If not, explicit padding is needed. Depending on the rocm version and the hardware, migraphx may check whether data preprocessing (padding and pack) are necessary, then sets different flags for rocblas API call.

2)  Add a pass to remove the Q/DQ for operator inputs if migraphx does not support the corresponding quantized operator 
     We need to add a QuantizeLinear and DeQuantizeLinear main operator, then add optimization either removing them or fusing them to corresponding quantized operator

3) Figure out the list of operators we have the quantized version
     MIGraphX can support int8 datatype for many operators, but cannot for others, we need to figure out the lists for each  of th

4) Figure out a general way to fuse the (DQ + operator), note that fused operator should be able to output fp32 datatype 

5) Optimize and fuse adjacent quantized operators, i.e., Q/DQ propagation, so more operators can run in int8 together with no additional quantization overhead for input data.

**Comment by pfultz2** [comment]
> Add a pass to remove the Q/DQ for operator inputs if migraphx does not support the corresponding quantized operator
We need to add a QuantizeLinear and DeQuantizeLinear main operator, then add optimization either removing them or fusing them to corresponding quantized operator

First we should have a pass to replace the DQ/OP/Q with the quantized operators, and then we can run a pass later to replace Q/DQ and DQ/Q pairs.

> Figure out a general way to fuse the (DQ + operator), note that fused operator should be able to output fp32 datatype

For convolution and gemms we need an API to pass the scale and offsets(other libraries do provide that). For the operators we implement, hopefully code gen or MLIR can generate a fused DQ/Q operator
