### ISSUE TITLE
Add Multinomial op

### ISSUE THREAD

**Issue by kahmed10** [ROCmSoftwarePlatform/AMDMIGraphX#821]

**Comment by causten** [comment]
Moved to 1.4 from 1.3 due to priority

**Comment by kahmed10** [comment]
Steps to implement basic functionality:

1. Create simple unit test in onnx, update parser to support Multinomial.

- if seed is not provided within operator, then randomly generate one and keep it fixed for the lifetime of the program.

2. randomly generate values of size (batch*samples) when parsing the operator and insert a literal into the program.
3. Implement ref and GPU compute methods, can use onnx runtime implementation as reference: https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/providers/cpu/generator/random.cc
4. Ensure test_verify() is able to fix the seed to constant value so that the unit test is deterministic.

The above will work for a single iteration, but to support multiple iterations, there needs to be a way to keep generating new random numbers and feeding them to the operator.
