### ISSUE TITLE
Support Unity Barracuda ONNX operators.

### ISSUE THREAD

**Issue by hgaspar** [ROCmSoftwarePlatform/AMDMIGraphX#824]
Goal:
To be able to support in migraphx models that are created via Barracuda under Unity. Barracuda is Unity's inference engine (onnx compatible), important in the windows (gaming) ecosystem. 

The list of desired operators are in:
https://docs.unity3d.com/Packages/com.unity.barracuda@1.4/manual/SupportedOperators.html

Let's go over them and identify gaps.

**Comment by kahmed10** [comment]
Operators we do not currently have support for:

- DepthToSpace
- Multinomial
- NonMaxSuppression
- RandomNormal
- RandomNormalLike
- RandomUniform
- RandomUniformLike
- SpaceToDepth
- TopK

**Comment by hgaspar** [comment]
Based on the list of gaps, here is a prioritization (feedback from client BU). A lower number means increased priority. We have a ticket for multinomial already. The random functions are also important, and we should probably address them together. Also TopK.   DepthToSpace,SpaceToDepth and nonMaxSuppression can be addressed in the future. 

•	DepthToSpace (4)
•	Multinomial (1)
•	NonMaxSuppression (5)
•	RandomNormal (3)
•	RandomNormalLike (3)
•	RandomUniform (3)
•	RandomUniformLike (3)
•	SpaceToDepth (4)
•	TopK (2)

**Comment by mvermeulen** [comment]
Add to release 1.3, particularly for the Random* operations.

**Comment by causten** [comment]
This issue will move to 1.4.  A new issue should be opened to split the operations in to manageable pieces

**Comment by causten** [comment]
SpaceToDepth is an "easier" one to add the "first label"

**Comment by causten** [comment]
The prioritized list of operators with issues attached to allow work to be completed over time...

• Multinomial (1) #821  
• DepthToSpace (4)  #905 #904
• NonMaxSuppression (5)  #866
• RandomNormal (3) #907
• RandomNormalLike (3) #907
• RandomUniform (3) #907
• RandomUniformLike (3) #907
• SpaceToDepth (4) 
• TopK (2) #877
