### ISSUE TITLE
"Instruction time" is not measured appropriately

### ISSUE THREAD

**Issue by hgaspar** [ROCmSoftwarePlatform/AMDMIGraphX#844]
Currently reported instruction times are measured as CPU-side wall times. This measurement includes overheads, such as for enqueueing kernel, and also writing back to global memory, and therefore it is an overestimate of the actual GPU-side time.  As a side effect of this, the wall time of executing a graph is greater than the sum of the wall times of the subparts, and on smaller graphs it can be significantly greater e.g. 5x).

It is very desirable for a variety of reasons to measure and report pure GPU-side kernel time. This can be accomplished via hip events, and roctracer library can be useful to that effect.

Among other reasons, this will enable having an objective idea regarding how good are various kernels inside migraphX, and therefore will provide valuable information regarding what are performance bottlenecks. This deserves a ticket on its own, and will be described/tracked separately.

**Comment by mvermeulen** [comment]
Adding to release 1.3, to see if we can record MIGraphX custom kernels first.

**Comment by causten** [comment]
Need new owner.  Work with Paul on the design.

**Comment by cagery** [comment]
Interested in it. Will work with Paul to see what's the best way to approach this.

**Comment by hgaspar** [comment]
After further investigation, roctracer does provide a convenient API.

It enables the following general design:
1. Call a start_tracing at beginning of inference frame that will reset profiling data for the frame 
2. Call a stop_tracing function at the end of the inference frame
3. While executing, hip API calls such as for memory transactions and kernel launch events will trigger a callback. From the callback, it is possible to retrieve the name of the kernel, and therefore use it to populate the profiling data for that kernel.  This assumes that a dictionary will be available between kernel names and pipeline subgraphs. This complication only pertains to the case where we want to do GPU timing of all kernels in a pipeline. However, timing just one kernel does not involve any such complications, and can be trivially supported with that model. 

Functioning code that shows a possible implementation of start_tracing/stop_tracing, and the callback function is in:

https://github.com/ROCm-Developer-Tools/roctracer/blob/amd-master/doc/roctracer_spec.md
