### ISSUE TITLE
an error: Shapes are not in standard layout

### ISSUE THREAD

**Issue by qianqing13579** [ROCmSoftwarePlatform/AMDMIGraphX#852]
I use a model to do inference,but an error occurs. the output:
amdmigraphx/src/include/migraphx/check_shapes.hpp:136: standard: softmax: Shapes are not in standard layout

the model link: https://pan.baidu.com/s/1BZ32JKuSt3r0VUZfTgM5Dw 
password：lz2l

**Comment by scxiao** [comment]
I tried the latest develop branch, it works well. Could you please try again?

**Comment by qianqing13579** [comment]
@scxiao ，what is the reason ?

**Comment by scxiao** [comment]
@qianqing13579 I cannot reproduce the problem, so no idea what is the reason..
Can you try the latest develop branch to see whether it works for you now?

**Comment by qianqing13579** [comment]
@scxiao ，I tried the latest develop branch, it works well. Thanks

**Comment by scxiao** [comment]
issue is not reproducible, so close this issue.
