### ISSUE TITLE
DepthToSpace support: DepthToSpace followed by Elementwise op (e.g. add)

### ISSUE THREAD

**Issue by hgaspar** [ROCmSoftwarePlatform/AMDMIGraphX#905]
Encoder-decoder pipelines, and ML-based upscaling pipelines employ processing steps where the output of a layer has greater spatial dimensions than the input. Initially, such layers were implemented in terms of a simple resize operation. The more modern approach is to use learnable resizing operations, such as deconvolutions, and convolutions+depth2space operations.

After the resizing operation (be in a simple nearest neighbor resizing), or a fancier deconvolution, or convolution+depth to space operation, a common operation that follows is an elementwise add, which combines the output of the previous layer (from depth to space), with a skip connection.

The present issue pertains only to pipelines that contain the following types of subgraph:

(depth to space -> buff 1)+ elementwise add (buff 0, buff 1), where buff 0 is from a skip connection.

In such cases, if depth to space can be viewed as a reshaping of the input tensor of add, and if buff 1 is only used by that add (a common case), then a beneficial fusion would be to never perform the depth to space explicitly, rather just reshape the corresponding input of the add operation.

Note:
convolution + depth2Space + add can be fused in two different ways:

1. (convolution + depth2Space) + add 
2. convolution + (depth2Space + add)

Those should be numerically equivalent, and timed (either manually, or in an autotuning scheme), to deduce what is the optimal approach, for a given pipeline.

**Comment by umangyadav** [comment]
#987 Solved this one for now. Closing this.
