### ISSUE TITLE
an error about broadcast

### ISSUE THREAD

**Issue by qianqing13579** [ROCmSoftwarePlatform/AMDMIGraphX#908]
The mobilenet_v2 model has an error that the outputs of each image is different when batchsize is 2. but If I insert a contiguous op after broadcast , the result will be right.The following attached file includes code,test image and outputs of each instruction. The result of adding contiguous is in output_addcontiguous.log. The output of the following instruction in output_addcontiguous.log is different with that in outpu.log.
main:@17 = gpu::add_clip(main:@9,main:@13,main:@15,main:@16,main:@14) -> half_type, {2, 32, 4, 4}, {512, 16, 4, 1}

the project link: https://pan.baidu.com/s/1LSQtapa7aB3sp7jn50v__w
password: k9i1

**Comment by scxiao** [comment]
@qianqing13579 What is the hardware that you are using?

**Comment by scxiao** [comment]
@qianqing13579 One more question, did you try the fp32? Are the results correctly without adding the contiguous?

**Comment by scxiao** [comment]
I ran the program on vega20 and mi100, respectively. For fp32, their results are the same (did not add contiguous); but for fp16, both results are different from that of fp32, and the fp16 result on vega20 and mi100 are also different.

**Comment by qianqing13579** [comment]
@scxiao  if I remove the line "migraphx::quantize_fp16()",the program has another problem.here is the output:

Memory access fault by GPU node-2 (Agent handle: 0x22704a0) on address (nil). Reason: Page not present or supervisor privilege.
Aborted (core dumped)

**Comment by qianqing13579** [comment]
@scxiao ,but if I add contiguous,the result of FP32 will be right!
