### ISSUE TITLE
Does MIGraphX support dynamic input shape?

### ISSUE THREAD

**Issue by qianqing13579** [ROCmSoftwarePlatform/AMDMIGraphX#915]
Does MIGraphX support dynamic input shape? for example, [8,3,512,512] (nchw) for the first inference, and [16,3,512,512] or [8,3,256,256] for the second inference.

**Comment by kahmed10** [comment]
This is something on our roadmap. In the example above, if you know the batch sizes in advance, you can compile multiple MIGraphX programs with different dimensions. This solution will work but is not going to be efficient memory-wise.
