### ISSUE TITLE
Upgrade our CI from ROCm4.2.0 to the latest supported release

### ISSUE THREAD

**Issue by causten** [ROCmSoftwarePlatform/AMDMIGraphX#941]
We use a stable ROCm driver as the basis for our CI tests.  As time moves on, so does ROCm.  The goal here is to upgrade our CI infrastructure to use the most recent ROCm.  It could be ROCm 4.3.0 or something newer.  To go above and beyond, the developer completing this assignment could design it in such a way that makes it easy to point to any ROCm driver.  After all, testing with a stable release is great but having the ability to test with a "still in development" driver on demand would be even better.

**Comment by kahmed10** [comment]
Opened  branch `docker-4.3.1` to track this.

**Comment by causten** [comment]
Issue #994 will resolve this issue
