### ISSUE TITLE
an error about shape::standard

### ISSUE THREAD

**Issue by qianqing13579** [ROCmSoftwarePlatform/AMDMIGraphX#978]
my model is as follows:
main:@395 = gpu::add(main:@357,main:@389,main:@394) -> float_type, {1, 32, 20, 20}, {12800, 400, 20, 1}
main:@402 = slice [axes={1},starts={16},ends={32}](main:@395) -> float_type, {1, 16, 20, 20}, {12800, 400, 20, 1}
main:@403 = gpu::leaky_relu [alpha=0.1](main:@402,main:@401) -> float_type, {1, 16, 20, 20}, {12800, 400, 20, 1}
I found that the output shape of slice is standard when I checked the output shape of slice. why? The standard output shape is  float_type, {1, 16, 20, 20}, {6400, 400, 20, 1},right?

**Comment by qianqing13579** [comment]
but when I set batchsize=2,the output shape of slice is float_type, {1, 16, 20, 20}, {12800, 400, 20, 1},and the shape is not standard

**Comment by scxiao** [comment]
@qianqing13579 If you take a look at the code to check standard shape, it is as:

```
        m_standard = this->elements() == this->element_space() and std::is_sorted(m_strides.rbegin(), m_strides.rend());
```
It means all the contents of the memory belong to the shape (no gap in the memory corresponding to the shape), and strides are sorted (no transpose). For batch size 1, since the out most dim is 1, so the output is a single chunk of memory, and there is no gap. But for batch size 2, there will be gaps in the memory corresponding to the shape, so it is not standard. 

So overall, it is an expected behavior.

**Comment by scxiao** [comment]
I see, you are talking about the scenario of "reshape after slice" with batch size 1 for the input of slice, then we do a reshape for the output of slice. 
Could you share the scenario that has a problem? I can take a look.

**Comment by qianqing13579** [comment]
@scxiao , I reshape a model from {1,3,640,640} to {2, 3, 64, 64}. so when the input is {1,3,640,640},the model is as follows:
main:@395 = gpu::add(main:@357,main:@389,main:@394) -> float_type, {1, 32, 20, 20}, {12800, 400, 20, 1}
main:@402 = slice axes={1},starts={16},ends={32} -> float_type, {1, 16, 20, 20}, {12800, 400, 20, 1}
main:@403 = gpu::leaky_relu alpha=0.1 -> float_type, {1, 16, 20, 20}, {12800, 400, 20, 1}
main:@406 = gpu::convolution[padding={1, 1, 1, 1},stride={1, 1},dilation={1, 1},group=1,padding_mode=0,solution_id=1](main:@403,main:@400,main:@404,main:@405) -> float_type, {1, 16, 20, 20}, {6400, 400, 20, 1}

but when the input is {2, 3, 64, 64},the model will be 
main:@395 = gpu::add(main:@357,main:@389,main:@394) -> float_type, {2, 32, 2, 2}, {128, 4, 2, 1}
main:@402 = slice axes={1},starts={16},ends={32} -> float_type, {2, 16, 2, 2}, {128, 4, 2, 1}
main:@403 = gpu::leaky_relu alpha=0.1 ->  float_type, {2, 16, 2, 2}, {128, 4, 2, 1}
and when the program run the instruction of main:@406 there will be an error: src/include/migraphx/check_shapes.hpp:136: standard: gpu::convolution: Shapes are not in standard layout.

but if I add a contiguous  op after slice,there will be no error.

**Comment by qianqing13579** [comment]
@scxiao ,I tried to implement the dynamic shape.could you please check the code and give me some advice? Please refer to issue #981 for more details.

**Comment by scxiao** [comment]
I took a look at the code. I have two comments:
1) The changes here may have limitation, which can cause incorrect results. So you may need to compare the output of this change to that using the right input shape to ensure results are correct.
2) Some optimizations are disabled which may affect performance.
