### ISSUE TITLE
change the mode attribute in pooling and roialign to an enum 

### ISSUE THREAD

**Issue by scxiao** [ROCmSoftwarePlatform/AMDMIGraphX#983]
In the pooling and roialign ops, there is a "mode" attribute for the pooling. Current implementation uses a string for the mode. We had better to change it to an enum type.

**Comment by bpickrel** [comment]
The only 2 enum values I see for mode in the  roialign code are "mode"and "avg"--what other values are possible?
Should attribute coord_trans_mode also become an enum?  (values:  half_pixel, output_half_pixel)

In pooling the same question applies.  The only value I see hard-coded is "average".

Should both of these uses of mode refer to the same enum, or use separate definitions?
